"""Unit tests for the onboarding injector (#148)."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from unittest.mock import patch

import pytest

from findajob.onboarding.injector import (
    _ALL_DESTINATIONS,
    _COMPANIES_OF_INTEREST_DEST,
    _SENTINEL_RELPATH,
    backup_existing,
    derive_companies_of_interest,
    inject,
    is_complete,
    mark_complete,
)

_MIN_FILES = {
    "profile.md": "# Profile\n",
    "master_resume.md": "# Resume\n",
    "target_companies.md": (
        "# Generated by findajob onboarding interviewer v2 — 2026-04-20\n\n"
        "## Tier 1 — Active Focus\n"
        "- Acme Corp\n"
        "- Example Industries — would take a role there today\n"
        "- Sample Systems (public benefit corp)\n\n"
        "## Tier 2 — Strong Interest\n"
        "- Other Co\n\n"
        "## Notes\n"
        "These are hypothetical.\n"
    ),
    "business_sector_employers_reference.md": "## Categories\n",
    "jsearch_queries.txt": "senior backend engineer\n",
    "prefilter_rules.yaml": "hard_rejects:\n  spam:\n    - '\\bspam\\b'\n",
    "in_domain_patterns.yaml": "positive:\n  - '\\bbackend\\b'\n",
    "display_name.txt": "Test Operator",
    "timezone.txt": "America/Los_Angeles",
    "ntfy_topic.txt": "tester-jobsearch-2026-17",
}


def test_all_destinations_map_required_filenames(tmp_path: Path) -> None:
    """Every plain-file ALLOWED_FILENAMES key has a destination — except env-merge ones."""
    from findajob.onboarding.injector import _ENV_MERGE_FILENAMES

    plain_files = {n for n in _MIN_FILES if n not in _ENV_MERGE_FILENAMES}
    assert set(_ALL_DESTINATIONS.keys()) == plain_files


def test_sentinel_and_companies_paths_are_stable() -> None:
    assert _SENTINEL_RELPATH == "data/.onboarding-complete"
    assert _COMPANIES_OF_INTEREST_DEST == "config/companies_of_interest.txt"


# ---- derive_companies_of_interest ----------------------------------------


def test_derive_tier1_strips_bullets_and_commentary() -> None:
    out = derive_companies_of_interest(_MIN_FILES["target_companies.md"])
    lines = [line for line in out.splitlines() if line]
    assert lines == ["Acme Corp", "Example Industries", "Sample Systems"]


def test_derive_ignores_tier2_and_beyond() -> None:
    md = (
        "## Tier 1 — Active Focus\n- A\n- B\n\n"
        "## Tier 2 — Strong Interest\n- C\n- D\n\n"
        "## Tier 3 — Opportunistic\n- E\n"
    )
    out = derive_companies_of_interest(md)
    assert out.splitlines() == ["A", "B"]


def test_derive_handles_star_bullets_and_numbered() -> None:
    md = "## Tier 1 — Active Focus\n* Alpha Co\n1. Beta Inc\n- Gamma LLC\n"
    out = derive_companies_of_interest(md)
    assert out.splitlines() == ["Alpha Co", "Beta Inc", "Gamma LLC"]


def test_derive_ends_with_newline() -> None:
    out = derive_companies_of_interest("## Tier 1\n- X\n")
    assert out.endswith("\n")


def test_derive_empty_when_no_tier1() -> None:
    assert derive_companies_of_interest("## Tier 2\n- Z\n") == ""


# ---- is_complete / mark_complete -----------------------------------------


def test_is_complete_false_on_empty_base(tmp_path: Path) -> None:
    assert is_complete(tmp_path) is False


def test_mark_and_is_complete_roundtrip(tmp_path: Path) -> None:
    mark_complete(tmp_path)
    assert is_complete(tmp_path) is True
    sentinel = tmp_path / "data" / ".onboarding-complete"
    assert sentinel.is_file()
    content = sentinel.read_text(encoding="utf-8").strip()
    # Parseable ISO 8601 UTC
    parsed = datetime.strptime(content, "%Y-%m-%dT%H:%M:%SZ")
    assert parsed.tzinfo is None  # naive from strptime; our write used Z


# ---- backup_existing ------------------------------------------------------


def test_backup_on_empty_base_short_circuits_no_mkdir(tmp_path: Path) -> None:
    """First onboarding on a fresh stack must NOT mkdir into .backups (#365).

    If the operator forgot the ``./state/.backups:/app/.backups`` bind mount,
    an unconditional mkdir would fail with EPERM (the parent ``/app`` is
    root-owned in the image). Short-circuiting when there's nothing to
    back up means first runs never touch that path — the bind mount is
    only required on re-runs, where there's actual existing state to
    preserve.
    """
    dest = backup_existing(tmp_path, "20260423T120000Z")
    # Returned path matches the contract, but is NOT created on disk
    # when the source set is empty.
    assert dest == tmp_path / ".backups" / "20260423T120000Z"
    assert not dest.exists()
    assert not (tmp_path / ".backups").exists()


def test_backup_when_only_one_source_exists_creates_dir(tmp_path: Path) -> None:
    """Single existing destination triggers normal backup flow."""
    (tmp_path / "candidate_context").mkdir()
    (tmp_path / "candidate_context" / "profile.md").write_text("p\n")
    dest = backup_existing(tmp_path, "20260423T120000Z")
    assert dest.is_dir()
    assert (dest / "candidate_context" / "profile.md").read_text() == "p\n"


def test_backup_copies_existing_destinations(tmp_path: Path) -> None:
    (tmp_path / "candidate_context").mkdir()
    (tmp_path / "candidate_context" / "profile.md").write_text("old profile\n")
    (tmp_path / "config").mkdir()
    (tmp_path / "config" / "prefilter_rules.yaml").write_text("hard_rejects: {}\n")
    (tmp_path / "data").mkdir()
    (tmp_path / "data" / ".onboarding-complete").write_text("2026-01-01T00:00:00Z\n")

    dest = backup_existing(tmp_path, "20260423T120000Z")
    assert (dest / "candidate_context" / "profile.md").read_text() == "old profile\n"
    assert (dest / "config" / "prefilter_rules.yaml").read_text() == "hard_rejects: {}\n"
    assert (dest / "data" / ".onboarding-complete").read_text() == "2026-01-01T00:00:00Z\n"


# ---- inject ---------------------------------------------------------------


def test_inject_writes_required_files_and_sentinel_and_derivation(tmp_path: Path) -> None:
    result = inject(tmp_path, _MIN_FILES, skip_smoke_check=True)
    assert result.backup_dir is not None  # returns the (possibly empty) backup dir
    # Discovery is exercised in the discoverer's own tests; here we only
    # confirm the result is shaped correctly. Discovery will fail in this
    # test environment because aichat-ng isn't on PATH, which is expected.
    assert result.discovery.success in (True, False)
    # Original seven canonical files
    assert (tmp_path / "candidate_context" / "profile.md").read_text() == _MIN_FILES["profile.md"]
    assert (tmp_path / "candidate_context" / "master_resume.md").read_text() == _MIN_FILES["master_resume.md"]
    assert (tmp_path / "config" / "target_companies.md").read_text() == _MIN_FILES["target_companies.md"]
    assert (tmp_path / "config" / "business_sector_employers_reference.md").read_text() == _MIN_FILES[
        "business_sector_employers_reference.md"
    ]
    assert (tmp_path / "config" / "jsearch_queries.txt").read_text() == _MIN_FILES["jsearch_queries.txt"]
    assert (tmp_path / "config" / "prefilter_rules.yaml").read_text() == _MIN_FILES["prefilter_rules.yaml"]
    assert (tmp_path / "config" / "in_domain_patterns.yaml").read_text() == _MIN_FILES["in_domain_patterns.yaml"]
    # New three: display_name, timezone, ntfy_topic — #328
    assert (tmp_path / "candidate_context" / "display_name.txt").read_text() == _MIN_FILES["display_name.txt"]
    assert (tmp_path / "data" / "timezone").read_text() == _MIN_FILES["timezone.txt"]
    # ntfy_topic.txt merges into data/.env, not a standalone file
    env_content = (tmp_path / "data" / ".env").read_text()
    assert "NTFY_TOPIC=tester-jobsearch-2026-17" in env_content
    # Derived companies_of_interest
    coi = (tmp_path / "config" / "companies_of_interest.txt").read_text()
    assert "Acme Corp" in coi
    assert "Example Industries" in coi
    # Sentinel
    sentinel = tmp_path / "data" / ".onboarding-complete"
    assert sentinel.is_file()


def test_inject_staging_failure_rolls_back(tmp_path: Path) -> None:
    """If staging (tempfile write) fails, no existing files are mutated and
    no partial backup remains.

    We simulate by making ``tempfile.mkstemp`` raise on its 3rd call. Inject
    must propagate, and leave the pre-existing file untouched with no
    tempfile residue and no backup directory.
    """
    # Pre-existing state — must survive the failed inject
    (tmp_path / "candidate_context").mkdir()
    (tmp_path / "candidate_context" / "profile.md").write_text("pre-existing\n")
    original = (tmp_path / "candidate_context" / "profile.md").read_text()

    import findajob.onboarding.injector as inj_mod

    calls = {"n": 0}
    real_mkstemp = inj_mod.tempfile.mkstemp

    def flaky_mkstemp(*args, **kwargs):
        calls["n"] += 1
        if calls["n"] == 3:
            raise OSError("simulated disk full")
        return real_mkstemp(*args, **kwargs)

    with patch.object(inj_mod.tempfile, "mkstemp", side_effect=flaky_mkstemp):
        with pytest.raises(OSError):
            inject(tmp_path, _MIN_FILES, skip_smoke_check=True)

    # profile.md unchanged
    assert (tmp_path / "candidate_context" / "profile.md").read_text() == original
    # No sentinel
    assert not (tmp_path / "data" / ".onboarding-complete").exists()
    # No derived file
    assert not (tmp_path / "config" / "companies_of_interest.txt").exists()
    # No residual tempfiles
    residual = list((tmp_path / "candidate_context").glob("profile.md.*.tmp"))
    assert residual == []
    # No backup dir left behind
    backups = tmp_path / ".backups"
    assert not backups.exists() or not any(backups.iterdir())


def test_inject_creates_parent_dirs(tmp_path: Path) -> None:
    # Fresh base with no subdirs — inject must mkdir them
    inject(tmp_path, _MIN_FILES, skip_smoke_check=True)
    assert (tmp_path / "candidate_context").is_dir()
    assert (tmp_path / "config").is_dir()
    assert (tmp_path / "data").is_dir()


def test_inject_raises_on_missing_file_in_parsed(tmp_path: Path) -> None:
    partial = {k: v for k, v in _MIN_FILES.items() if k != "profile.md"}
    with pytest.raises(ValueError, match="profile.md"):
        inject(tmp_path, partial, skip_smoke_check=True)


# ── voice-samples.md handling (#262) ────────────────────────────────────────


def _full_files_with_voice(voice_body: str) -> dict[str, str]:
    return {**_MIN_FILES, "voice-samples.md": voice_body}


def test_inject_omits_voice_samples_when_absent(tmp_path: Path) -> None:
    """No voice-samples.md → file is never created on disk, no error."""
    inject(tmp_path, _MIN_FILES, skip_smoke_check=True)
    voice_dest = tmp_path / "candidate_context" / "voice_samples" / "voice-samples.md"
    assert not voice_dest.exists()


def test_inject_writes_voice_samples_when_present(tmp_path: Path) -> None:
    """When voice-samples.md is provided, the file lands at the canonical path."""
    voice_body = "I lived for quite a while in this house. Things got bad before they got better."
    with patch("findajob.onboarding.injector.process_voice_samples") as mock_process:
        # Bypass LLM redaction in tests; return cleaned identity
        mock_process.return_value = (voice_body, True)
        inject(tmp_path, _full_files_with_voice(voice_body), skip_smoke_check=True)
    voice_dest = tmp_path / "candidate_context" / "voice_samples" / "voice-samples.md"
    assert voice_dest.exists()
    assert voice_dest.read_text(encoding="utf-8") == voice_body


def test_inject_runs_process_voice_samples_with_redact_flag(tmp_path: Path) -> None:
    """The process_voice_samples helper is called with the inject() flag value."""
    voice_body = "Some prose here."
    with patch("findajob.onboarding.injector.process_voice_samples") as mock_process:
        mock_process.return_value = ("processed text", True)
        inject(
            tmp_path,
            _full_files_with_voice(voice_body),
            redact_voice_samples=False,
            skip_smoke_check=True,
        )
        mock_process.assert_called_once_with(voice_body, redact=False)


def test_inject_skips_voice_write_when_processing_returns_empty(tmp_path: Path) -> None:
    """If cleaning empties the body (all-structural input), no file is written."""
    voice_body = "# Just A Header\n\n---"
    with patch("findajob.onboarding.injector.process_voice_samples") as mock_process:
        mock_process.return_value = ("", True)
        inject(tmp_path, _full_files_with_voice(voice_body), skip_smoke_check=True)
    voice_dest = tmp_path / "candidate_context" / "voice_samples" / "voice-samples.md"
    assert not voice_dest.exists()


def test_inject_creates_voice_samples_parent_dir(tmp_path: Path) -> None:
    """The candidate_context/voice_samples/ directory is created if missing."""
    voice_body = "Real prose."
    with patch("findajob.onboarding.injector.process_voice_samples") as mock_process:
        mock_process.return_value = (voice_body, True)
        inject(tmp_path, _full_files_with_voice(voice_body), skip_smoke_check=True)
    voice_dir = tmp_path / "candidate_context" / "voice_samples"
    assert voice_dir.is_dir()


def test_inject_backs_up_existing_voice_samples_file(tmp_path: Path) -> None:
    """An existing voice-samples.md is copied to .backups/ before being overwritten."""
    voice_dir = tmp_path / "candidate_context" / "voice_samples"
    voice_dir.mkdir(parents=True)
    existing = voice_dir / "voice-samples.md"
    existing.write_text("OLD voice content.", encoding="utf-8")

    with patch("findajob.onboarding.injector.process_voice_samples") as mock_process:
        mock_process.return_value = ("NEW voice content.", True)
        inject(tmp_path, _full_files_with_voice("anything"), skip_smoke_check=True)

    # Final state: new content
    assert existing.read_text(encoding="utf-8") == "NEW voice content."
    # Backup contains old content
    backup_root = tmp_path / ".backups"
    backups = list(backup_root.iterdir()) if backup_root.exists() else []
    assert backups, "Expected a backup directory"
    backed_up = backups[0] / "candidate_context" / "voice_samples" / "voice-samples.md"
    assert backed_up.exists()
    assert backed_up.read_text(encoding="utf-8") == "OLD voice content."


def test_inject_discovery_hook_soft_fails_when_aichat_missing(tmp_path: Path, monkeypatch) -> None:
    """When aichat-ng isn't available, inject() returns success=True for the
    file commit but discovery.success=False. Sentinel is still written.
    """
    # Force the discoverer's subprocess call to fail
    import findajob.discoverer.runner as run_mod

    def boom(*a, **kw):
        raise FileNotFoundError("simulated: aichat-ng not on PATH")

    monkeypatch.setattr(run_mod.subprocess, "run", boom)

    result = inject(tmp_path, _MIN_FILES, skip_smoke_check=True)
    # Sentinel was written (onboarding succeeded)
    assert (tmp_path / "data" / ".onboarding-complete").is_file()
    # Discovery soft-failed
    assert result.discovery.success is False
    assert result.discovery.error is not None


# ── #328: env merge + smoke check + new collected fields ───────────────────


def test_merge_env_content_replaces_existing_keys() -> None:
    """Existing KEY=value lines get their value replaced; everything else preserved."""
    from findajob.onboarding.injector import merge_env_content

    existing = (
        "# header comment\nOPENROUTER_API_KEY=old-key\nRAPIDAPI_KEY=should-stay\n\n# section\nNTFY_TOPIC=old-topic\n"
    )
    merged = merge_env_content(existing, "", {"OPENROUTER_API_KEY": "new-key", "NTFY_TOPIC": "new-topic"})
    assert "OPENROUTER_API_KEY=new-key" in merged
    assert "NTFY_TOPIC=new-topic" in merged
    assert "RAPIDAPI_KEY=should-stay" in merged
    assert "old-key" not in merged
    assert "old-topic" not in merged
    # Comments and blank lines preserved
    assert "# header comment" in merged
    assert "# section" in merged


def test_merge_env_content_appends_new_keys() -> None:
    """Keys that aren't in existing get appended at the end."""
    from findajob.onboarding.injector import merge_env_content

    existing = "RAPIDAPI_KEY=keep-me\n"
    merged = merge_env_content(existing, "", {"OPENROUTER_API_KEY": "fresh"})
    assert "RAPIDAPI_KEY=keep-me" in merged
    assert merged.rstrip().endswith("OPENROUTER_API_KEY=fresh")


def test_merge_env_content_uses_example_when_existing_empty() -> None:
    """Fresh install: no .env yet, use .env.example as the starting template."""
    from findajob.onboarding.injector import merge_env_content

    example = "OPENROUTER_API_KEY=your_key_here\nRAPIDAPI_KEY=your_key_here\n"
    merged = merge_env_content("", example, {"OPENROUTER_API_KEY": "real-key"})
    assert "OPENROUTER_API_KEY=real-key" in merged
    assert "RAPIDAPI_KEY=your_key_here" in merged  # placeholder for unrelated key preserved


def test_inject_with_openrouter_key_writes_to_env(tmp_path: Path) -> None:
    """The form-field key lands in data/.env as OPENROUTER_API_KEY=..."""
    inject(tmp_path, _MIN_FILES, openrouter_api_key="sk-or-v1-test", skip_smoke_check=True)
    env_content = (tmp_path / "data" / ".env").read_text()
    assert "OPENROUTER_API_KEY=sk-or-v1-test" in env_content


def test_inject_env_file_has_chmod_600(tmp_path: Path) -> None:
    """data/.env is sensitive — must be 0600 after write."""
    import stat as stat_mod

    inject(tmp_path, _MIN_FILES, openrouter_api_key="sk-or-v1-test", skip_smoke_check=True)
    env_path = tmp_path / "data" / ".env"
    mode = env_path.stat().st_mode & 0o777
    assert mode == 0o600, f"expected 0o600, got {stat_mod.filemode(env_path.stat().st_mode)}"


def test_inject_smoke_check_failure_raises_and_skips_sentinel(tmp_path: Path, monkeypatch) -> None:
    """When verify_openrouter_key returns (False, error), inject raises
    OnboardingSmokeCheckFailed and the sentinel is NOT written. Files have
    already been committed (next paste-back will overwrite cleanly)."""
    import findajob.onboarding.injector as inj_mod
    from findajob.onboarding import OnboardingSmokeCheckFailed

    def fake_verify(_key):
        return False, "simulated 401 from OpenRouter"

    monkeypatch.setattr(inj_mod, "verify_openrouter_key", fake_verify)

    with pytest.raises(OnboardingSmokeCheckFailed) as excinfo:
        inject(tmp_path, _MIN_FILES, openrouter_api_key="bad-key")
    assert "simulated 401" in excinfo.value.user_message
    # Files committed; sentinel is NOT
    assert (tmp_path / "candidate_context" / "profile.md").exists()
    assert not (tmp_path / "data" / ".onboarding-complete").exists()


def test_inject_smoke_check_pass_writes_sentinel(tmp_path: Path, monkeypatch) -> None:
    """When verify_openrouter_key returns (True, None), sentinel is written."""
    import findajob.onboarding.injector as inj_mod

    def fake_verify(_key):
        return True, None

    monkeypatch.setattr(inj_mod, "verify_openrouter_key", fake_verify)

    inject(tmp_path, _MIN_FILES, openrouter_api_key="sk-or-v1-good")
    assert (tmp_path / "data" / ".onboarding-complete").is_file()


def test_inject_writes_display_name_file(tmp_path: Path) -> None:
    """display_name.txt → candidate_context/display_name.txt (single line)."""
    inject(tmp_path, _MIN_FILES, skip_smoke_check=True)
    assert (tmp_path / "candidate_context" / "display_name.txt").read_text() == "Test Operator"


def test_inject_writes_timezone_file(tmp_path: Path) -> None:
    """timezone.txt → data/timezone (no extension; matches Unix convention)."""
    inject(tmp_path, _MIN_FILES, skip_smoke_check=True)
    assert (tmp_path / "data" / "timezone").read_text() == "America/Los_Angeles"


def test_inject_ntfy_topic_strips_key_prefix(tmp_path: Path) -> None:
    """Body 'NTFY_TOPIC=foo-bar' yields just 'foo-bar' in data/.env."""
    files = {**_MIN_FILES, "ntfy_topic.txt": "NTFY_TOPIC=judy-jobsearch-2026-17"}
    inject(tmp_path, files, skip_smoke_check=True)
    env_content = (tmp_path / "data" / ".env").read_text()
    assert "NTFY_TOPIC=judy-jobsearch-2026-17" in env_content
    # No nested NTFY_TOPIC=NTFY_TOPIC=... shape
    assert "NTFY_TOPIC=NTFY_TOPIC" not in env_content


def test_inject_ntfy_topic_accepts_bare_value(tmp_path: Path) -> None:
    """Body 'just-the-topic' (no KEY= prefix) works too."""
    files = {**_MIN_FILES, "ntfy_topic.txt": "judy-jobsearch-2026-17"}
    inject(tmp_path, files, skip_smoke_check=True)
    env_content = (tmp_path / "data" / ".env").read_text()
    assert "NTFY_TOPIC=judy-jobsearch-2026-17" in env_content


def test_inject_ntfy_topic_empty_body_raises(tmp_path: Path) -> None:
    """An empty ntfy_topic.txt fails loudly rather than silently writing nothing."""
    files = {**_MIN_FILES, "ntfy_topic.txt": "   \n  \n"}
    with pytest.raises(ValueError, match="ntfy_topic"):
        inject(tmp_path, files, skip_smoke_check=True)


def test_inject_preserves_other_env_keys(tmp_path: Path) -> None:
    """A pre-existing .env (with RAPIDAPI_KEY etc.) is preserved across the merge."""
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    (data_dir / ".env").write_text(
        "OPENROUTER_API_KEY=old-shared-key\nRAPIDAPI_KEY=preserve-me\nGOOGLE_API_KEY=preserve-me-too\n"
    )
    inject(tmp_path, _MIN_FILES, openrouter_api_key="user-own-key", skip_smoke_check=True)
    env_content = (data_dir / ".env").read_text()
    assert "OPENROUTER_API_KEY=user-own-key" in env_content
    assert "old-shared-key" not in env_content
    assert "RAPIDAPI_KEY=preserve-me" in env_content
    assert "GOOGLE_API_KEY=preserve-me-too" in env_content
