"""Unit tests for the onboarding injector (#148)."""

from __future__ import annotations

import json
import os
import sqlite3
from datetime import datetime
from pathlib import Path
from unittest.mock import patch

import pytest

from findajob.onboarding.injector import (
    _ALL_DESTINATIONS,
    _SENTINEL_RELPATH,
    backup_existing,
    inject,
    is_complete,
    mark_complete,
)
from findajob.onboarding.parser import ALLOWED_FILENAMES

_MIN_FILES = {
    "profile.md": "# Profile\n",
    "master_resume.md": "# Resume\n",
    "target_companies.md": (
        "# Generated by findajob onboarding interviewer v2 — 2026-04-20\n\n"
        "## Tier 1 — Active Focus\n"
        "- Acme Corp\n"
        "- Example Industries — would take a role there today\n"
        "- Sample Systems (public benefit corp)\n\n"
        "## Tier 2 — Strong Interest\n"
        "- Other Co\n\n"
        "## Notes\n"
        "These are hypothetical.\n"
    ),
    "business_sector_employers_reference.md": "## Categories\n",
    "jsearch_queries.txt": "senior backend engineer\n",
    "prefilter_rules.yaml": "hard_rejects:\n  spam:\n    - '\\bspam\\b'\n",
    "in_domain_patterns.yaml": "positive:\n  - '\\bbackend\\b'\n",
    "reject_reasons.yaml": (
        "reasons:\n  - 'Skills Mismatch'\n  - 'Already Applied'\n  - 'Other'\n"
        "title_signal_reasons:\n  - 'Skills Mismatch'\n"
    ),
    "display_name.txt": "Test Operator",
    "timezone.txt": "America/Los_Angeles",
    "ntfy_topic.txt": "tester-jobsearch-2026-17",
}


def _minimal_found_dict() -> dict[str, str]:
    """Build the minimum 'found' dict that injector.inject() requires (all ALLOWED present).

    Excludes optional source-config files (jsearch_queries.txt, feed-urls.txt,
    linkedin-alerts.md) — tests that want them add them individually.
    """
    return {
        "profile.md": "# Profile\n## Identity\nTest User\n",
        "master_resume.md": "# Resume\n## Contact\nTest User\n",
        "target_companies.md": "## Tier 1 — Active Focus\n- Acme\n",
        "business_sector_employers_reference.md": "## Categories\n### Foo\n- Acme\n",
        "prefilter_rules.yaml": "hard_rejects:\n  spam:\n    - '\\bspam\\b'\n",
        "in_domain_patterns.yaml": "positive:\n  - '\\bbackend\\s+engineer\\b'\n",
        "reject_reasons.yaml": (
            "reasons:\n  - 'Skills Mismatch'\n  - 'Already Applied'\n  - 'Other'\n"
            "title_signal_reasons:\n  - 'Skills Mismatch'\n"
        ),
        "display_name.txt": "Test User",
        "timezone.txt": "America/Los_Angeles",
        "ntfy_topic.txt": "test-topic-2026",
    }


def test_all_destinations_map_required_filenames(tmp_path: Path) -> None:
    """Every plain-file ALLOWED_FILENAMES key has a destination — except env-merge ones.

    jsearch_queries.txt is OPTIONAL (moved to _OPTIONAL_DESTINATIONS in #283), so it
    should NOT appear in _ALL_DESTINATIONS.  Compare against ALLOWED_FILENAMES directly
    rather than _MIN_FILES to keep this invariant tight.
    """
    from findajob.onboarding.injector import _ENV_MERGE_FILENAMES

    plain_required = {n for n in ALLOWED_FILENAMES if n not in _ENV_MERGE_FILENAMES}
    assert set(_ALL_DESTINATIONS.keys()) == plain_required


def test_sentinel_path_is_stable() -> None:
    assert _SENTINEL_RELPATH == "data/.onboarding-complete"


# ---- is_complete / mark_complete -----------------------------------------


def test_is_complete_false_on_empty_base(tmp_path: Path) -> None:
    assert is_complete(tmp_path) is False


def test_mark_and_is_complete_roundtrip(tmp_path: Path) -> None:
    mark_complete(tmp_path)
    assert is_complete(tmp_path) is True
    sentinel = tmp_path / "data" / ".onboarding-complete"
    assert sentinel.is_file()
    content = sentinel.read_text(encoding="utf-8").strip()
    # Parseable ISO 8601 UTC
    parsed = datetime.strptime(content, "%Y-%m-%dT%H:%M:%SZ")
    assert parsed.tzinfo is None  # naive from strptime; our write used Z


# ---- backup_existing ------------------------------------------------------


def test_backup_on_empty_base_short_circuits_no_mkdir(tmp_path: Path) -> None:
    """First onboarding on a fresh stack must NOT mkdir into .backups (#365).

    If the operator forgot the ``./state/.backups:/app/.backups`` bind mount,
    an unconditional mkdir would fail with EPERM (the parent ``/app`` is
    root-owned in the image). Short-circuiting when there's nothing to
    back up means first runs never touch that path — the bind mount is
    only required on re-runs, where there's actual existing state to
    preserve.
    """
    dest = backup_existing(tmp_path, "20260423T120000Z")
    # Returned path matches the contract, but is NOT created on disk
    # when the source set is empty.
    assert dest == tmp_path / ".backups" / "20260423T120000Z"
    assert not dest.exists()
    assert not (tmp_path / ".backups").exists()


def test_backup_when_only_one_source_exists_creates_dir(tmp_path: Path) -> None:
    """Single existing destination triggers normal backup flow."""
    (tmp_path / "candidate_context").mkdir()
    (tmp_path / "candidate_context" / "profile.md").write_text("p\n")
    dest = backup_existing(tmp_path, "20260423T120000Z")
    assert dest.is_dir()
    assert (dest / "candidate_context" / "profile.md").read_text() == "p\n"


def test_backup_copies_existing_destinations(tmp_path: Path) -> None:
    (tmp_path / "candidate_context").mkdir()
    (tmp_path / "candidate_context" / "profile.md").write_text("old profile\n")
    (tmp_path / "config").mkdir()
    (tmp_path / "config" / "prefilter_rules.yaml").write_text("hard_rejects: {}\n")
    (tmp_path / "data").mkdir()
    (tmp_path / "data" / ".onboarding-complete").write_text("2026-01-01T00:00:00Z\n")

    dest = backup_existing(tmp_path, "20260423T120000Z")
    assert (dest / "candidate_context" / "profile.md").read_text() == "old profile\n"
    assert (dest / "config" / "prefilter_rules.yaml").read_text() == "hard_rejects: {}\n"
    assert (dest / "data" / ".onboarding-complete").read_text() == "2026-01-01T00:00:00Z\n"


# ---- inject ---------------------------------------------------------------


def test_inject_writes_required_files_and_sentinel_and_derivation(tmp_path: Path) -> None:
    result = inject(tmp_path, _MIN_FILES, skip_smoke_check=True)
    assert result.backup_dir is not None  # returns the (possibly empty) backup dir
    # Discovery is exercised in the discoverer's own tests; here we only
    # confirm the result is shaped correctly. Discovery will fail in this
    # test environment because aichat-ng isn't on PATH, which is expected.
    assert result.discovery.success in (True, False)
    # Original seven canonical files
    assert (tmp_path / "candidate_context" / "profile.md").read_text() == _MIN_FILES["profile.md"]
    assert (tmp_path / "candidate_context" / "master_resume.md").read_text() == _MIN_FILES["master_resume.md"]
    assert (tmp_path / "config" / "target_companies.md").read_text() == _MIN_FILES["target_companies.md"]
    assert (tmp_path / "config" / "business_sector_employers_reference.md").read_text() == _MIN_FILES[
        "business_sector_employers_reference.md"
    ]
    assert (tmp_path / "config" / "jsearch_queries.txt").read_text() == _MIN_FILES["jsearch_queries.txt"]
    assert (tmp_path / "config" / "prefilter_rules.yaml").read_text() == _MIN_FILES["prefilter_rules.yaml"]
    assert (tmp_path / "config" / "in_domain_patterns.yaml").read_text() == _MIN_FILES["in_domain_patterns.yaml"]
    # New three: display_name, timezone, ntfy_topic — #328
    assert (tmp_path / "candidate_context" / "display_name.txt").read_text() == _MIN_FILES["display_name.txt"]
    assert (tmp_path / "data" / "timezone").read_text() == _MIN_FILES["timezone.txt"]
    # ntfy_topic.txt merges into data/.env, not a standalone file
    env_content = (tmp_path / "data" / ".env").read_text()
    assert "NTFY_TOPIC=tester-jobsearch-2026-17" in env_content
    # Sentinel: per #407, inject() never writes the sentinel directly — every
    # onboarding flow now ends at the Gmail-config gate's /finish endpoint,
    # which writes the sentinel after the user verifies+saves an IMAP
    # credential pair (or explicitly skips).
    sentinel = tmp_path / "data" / ".onboarding-complete"
    assert not sentinel.exists()


def test_inject_staging_failure_rolls_back(tmp_path: Path) -> None:
    """If staging (tempfile write) fails, no existing files are mutated and
    no partial backup remains.

    We simulate by making ``tempfile.mkstemp`` raise on its 3rd call. Inject
    must propagate, and leave the pre-existing file untouched with no
    tempfile residue and no backup directory.
    """
    # Pre-existing state — must survive the failed inject
    (tmp_path / "candidate_context").mkdir()
    (tmp_path / "candidate_context" / "profile.md").write_text("pre-existing\n")
    original = (tmp_path / "candidate_context" / "profile.md").read_text()

    import findajob.onboarding.injector as inj_mod

    calls = {"n": 0}
    real_mkstemp = inj_mod.tempfile.mkstemp

    def flaky_mkstemp(*args, **kwargs):
        calls["n"] += 1
        if calls["n"] == 3:
            raise OSError("simulated disk full")
        return real_mkstemp(*args, **kwargs)

    with patch.object(inj_mod.tempfile, "mkstemp", side_effect=flaky_mkstemp):
        with pytest.raises(OSError):
            inject(tmp_path, _MIN_FILES, skip_smoke_check=True)

    # profile.md unchanged
    assert (tmp_path / "candidate_context" / "profile.md").read_text() == original
    # No sentinel
    assert not (tmp_path / "data" / ".onboarding-complete").exists()
    # No residual tempfiles
    residual = list((tmp_path / "candidate_context").glob("profile.md.*.tmp"))
    assert residual == []
    # WIDEN: assert no *.tmp residue anywhere in the tree, not just for one filename
    leftover_anywhere = list(tmp_path.rglob("*.tmp"))
    assert leftover_anywhere == [], f"rollback left tempfile residue: {leftover_anywhere}"
    # No backup dir left behind
    backups = tmp_path / ".backups"
    assert not backups.exists() or not any(backups.iterdir())


def test_inject_creates_parent_dirs(tmp_path: Path) -> None:
    # Fresh base with no subdirs — inject must mkdir them
    inject(tmp_path, _MIN_FILES, skip_smoke_check=True)
    assert (tmp_path / "candidate_context").is_dir()
    assert (tmp_path / "config").is_dir()
    assert (tmp_path / "data").is_dir()


def test_inject_raises_on_missing_file_in_parsed(tmp_path: Path) -> None:
    partial = {k: v for k, v in _MIN_FILES.items() if k != "profile.md"}
    with pytest.raises(ValueError, match="profile.md"):
        inject(tmp_path, partial, skip_smoke_check=True)


# ── voice-samples.md handling (#262) ────────────────────────────────────────


def _full_files_with_voice(voice_body: str) -> dict[str, str]:
    return {**_MIN_FILES, "voice-samples.md": voice_body}


def test_inject_omits_voice_samples_when_absent(tmp_path: Path) -> None:
    """No voice-samples.md → file is never created on disk, no error."""
    inject(tmp_path, _MIN_FILES, skip_smoke_check=True)
    voice_dest = tmp_path / "candidate_context" / "voice_samples" / "voice-samples.md"
    assert not voice_dest.exists()


def test_inject_writes_voice_samples_when_present(tmp_path: Path) -> None:
    """When voice-samples.md is provided, the file lands at the canonical path."""
    voice_body = "I lived for quite a while in this house. Things got bad before they got better."
    with patch("findajob.onboarding.injector.process_voice_samples") as mock_process:
        # Bypass LLM redaction in tests; return cleaned identity
        mock_process.return_value = (voice_body, True)
        inject(tmp_path, _full_files_with_voice(voice_body), skip_smoke_check=True)
    voice_dest = tmp_path / "candidate_context" / "voice_samples" / "voice-samples.md"
    assert voice_dest.exists()
    assert voice_dest.read_text(encoding="utf-8") == voice_body


def test_inject_runs_process_voice_samples_with_redact_flag(tmp_path: Path) -> None:
    """The process_voice_samples helper is called with the inject() flag value."""
    voice_body = "Some prose here."
    with patch("findajob.onboarding.injector.process_voice_samples") as mock_process:
        mock_process.return_value = ("processed text", True)
        inject(
            tmp_path,
            _full_files_with_voice(voice_body),
            redact_voice_samples=False,
            skip_smoke_check=True,
        )
        mock_process.assert_called_once_with(voice_body, redact=False, conn=None)


def test_inject_skips_voice_write_when_processing_returns_empty(tmp_path: Path) -> None:
    """If cleaning empties the body (all-structural input), no file is written."""
    voice_body = "# Just A Header\n\n---"
    with patch("findajob.onboarding.injector.process_voice_samples") as mock_process:
        mock_process.return_value = ("", True)
        inject(tmp_path, _full_files_with_voice(voice_body), skip_smoke_check=True)
    voice_dest = tmp_path / "candidate_context" / "voice_samples" / "voice-samples.md"
    assert not voice_dest.exists()


def test_inject_creates_voice_samples_parent_dir(tmp_path: Path) -> None:
    """The candidate_context/voice_samples/ directory is created if missing."""
    voice_body = "Real prose."
    with patch("findajob.onboarding.injector.process_voice_samples") as mock_process:
        mock_process.return_value = (voice_body, True)
        inject(tmp_path, _full_files_with_voice(voice_body), skip_smoke_check=True)
    voice_dir = tmp_path / "candidate_context" / "voice_samples"
    assert voice_dir.is_dir()


def test_inject_backs_up_existing_voice_samples_file(tmp_path: Path) -> None:
    """An existing voice-samples.md is copied to .backups/ before being overwritten."""
    voice_dir = tmp_path / "candidate_context" / "voice_samples"
    voice_dir.mkdir(parents=True)
    existing = voice_dir / "voice-samples.md"
    existing.write_text("OLD voice content.", encoding="utf-8")

    with patch("findajob.onboarding.injector.process_voice_samples") as mock_process:
        mock_process.return_value = ("NEW voice content.", True)
        inject(tmp_path, _full_files_with_voice("anything"), skip_smoke_check=True)

    # Final state: new content
    assert existing.read_text(encoding="utf-8") == "NEW voice content."
    # Backup contains old content
    backup_root = tmp_path / ".backups"
    backups = list(backup_root.iterdir()) if backup_root.exists() else []
    assert backups, "Expected a backup directory"
    backed_up = backups[0] / "candidate_context" / "voice_samples" / "voice-samples.md"
    assert backed_up.exists()
    assert backed_up.read_text(encoding="utf-8") == "OLD voice content."


_COST_LOG_SCHEMA = """
CREATE TABLE cost_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id TEXT,
    operation TEXT NOT NULL,
    model TEXT NOT NULL,
    latency_ms INTEGER,
    success INTEGER DEFAULT 1,
    error_message TEXT,
    logged_at TEXT DEFAULT (datetime('now')),
    input_tokens INTEGER,
    output_tokens INTEGER,
    cost_usd REAL
);
"""


def _stub_openrouter_response(cost: float = 0.005, prompt_tokens: int = 400, completion_tokens: int = 120):
    body = json.dumps(
        {
            "id": "gen-vp-test",
            "choices": [{"message": {"content": "Generalized prose output."}}],
            "usage": {
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "cost": cost,
                "prompt_tokens_details": {"cached_tokens": 0},
            },
        }
    ).encode("utf-8")

    class _Resp:
        def __enter__(self):
            return self

        def __exit__(self, *a):
            pass

        def read(self):
            return body

    return _Resp()


def test_inject_with_conn_writes_voice_processor_cost_log(tmp_path: Path) -> None:
    """End-to-end: inject() with conn + voice-samples.md writes exactly one
    cost_log row with operation='voice_processor' and API-authoritative cost.

    Closes the #471 wiring gap (#481): the production call site now plumbs
    a sqlite connection through inject → process_voice_samples → redact_voice_samples
    so voice-processor LLM cost lands in cost_log alongside every other call site.
    """
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    conn.executescript(_COST_LOG_SCHEMA)

    voice_body = "I lived for quite a while in this house. Things got bad before they got better."

    with (
        patch.dict(os.environ, {"OPENROUTER_API_KEY": "sk-or-v1-test"}),
        patch(
            "findajob.llm.openrouter.urllib.request.urlopen",
            return_value=_stub_openrouter_response(cost=0.005, prompt_tokens=400, completion_tokens=120),
        ),
    ):
        inject(tmp_path, _full_files_with_voice(voice_body), conn=conn, skip_smoke_check=True)

    # Exactly one row: the discoverer runs in a subprocess at the tail of inject(),
    # so its complete() call doesn't share this process's urlopen patch and doesn't
    # contribute to the parent conn's cost_log. If the discoverer is ever made
    # in-process this count rises to two — the regression is real, not a test bug.
    rows = conn.execute("SELECT operation, cost_usd, input_tokens, output_tokens, success FROM cost_log").fetchall()
    assert len(rows) == 1, f"Expected exactly one cost_log row, got {len(rows)}"
    row = rows[0]
    assert row["operation"] == "voice_processor"
    assert row["cost_usd"] == 0.005
    assert row["input_tokens"] == 400
    assert row["output_tokens"] == 120
    assert row["success"] == 1


def test_inject_without_conn_skips_cost_log(tmp_path: Path) -> None:
    """Backwards-compat: inject() called without conn still processes voice
    samples, just doesn't log cost — matches pre-#481 behavior.
    """
    voice_body = "Some prose."
    with patch("findajob.onboarding.injector.process_voice_samples") as mock_process:
        mock_process.return_value = (voice_body, True)
        inject(tmp_path, _full_files_with_voice(voice_body), skip_smoke_check=True)
        mock_process.assert_called_once_with(voice_body, redact=True, conn=None)


def test_inject_discovery_hook_soft_fails_when_aichat_missing(tmp_path: Path, monkeypatch) -> None:
    """When aichat-ng isn't available, inject() returns success=True for the
    file commit but discovery.success=False. Sentinel is still written.
    """
    # Force the discoverer's subprocess call to fail
    import findajob.discoverer.runner as run_mod

    def boom(*a, **kw):
        raise FileNotFoundError("simulated: aichat-ng not on PATH")

    monkeypatch.setattr(run_mod.subprocess, "run", boom)

    result = inject(tmp_path, _MIN_FILES, skip_smoke_check=True)
    # Sentinel deferred to the Gmail-config gate's /finish (#407) — onboarding
    # success up to inject() is signalled by the absence of an exception, not
    # by sentinel existence.
    assert not (tmp_path / "data" / ".onboarding-complete").exists()
    # Discovery soft-failed
    assert result.discovery.success is False
    assert result.discovery.error is not None


# ── #328: env merge + smoke check + new collected fields ───────────────────


def test_merge_env_content_replaces_existing_keys() -> None:
    """Existing KEY=value lines get their value replaced; everything else preserved."""
    from findajob.onboarding.injector import merge_env_content

    existing = (
        "# header comment\nOPENROUTER_API_KEY=old-key\nRAPIDAPI_KEY=should-stay\n\n# section\nNTFY_TOPIC=old-topic\n"
    )
    merged = merge_env_content(existing, "", {"OPENROUTER_API_KEY": "new-key", "NTFY_TOPIC": "new-topic"})
    assert "OPENROUTER_API_KEY=new-key" in merged
    assert "NTFY_TOPIC=new-topic" in merged
    assert "RAPIDAPI_KEY=should-stay" in merged
    assert "old-key" not in merged
    assert "old-topic" not in merged
    # Comments and blank lines preserved
    assert "# header comment" in merged
    assert "# section" in merged


def test_merge_env_content_appends_new_keys() -> None:
    """Keys that aren't in existing get appended at the end."""
    from findajob.onboarding.injector import merge_env_content

    existing = "RAPIDAPI_KEY=keep-me\n"
    merged = merge_env_content(existing, "", {"OPENROUTER_API_KEY": "fresh"})
    assert "RAPIDAPI_KEY=keep-me" in merged
    assert merged.rstrip().endswith("OPENROUTER_API_KEY=fresh")


def test_merge_env_content_uses_example_when_existing_empty() -> None:
    """Fresh install: no .env yet, use .env.example as the starting template."""
    from findajob.onboarding.injector import merge_env_content

    example = "OPENROUTER_API_KEY=your_key_here\nRAPIDAPI_KEY=your_key_here\n"
    merged = merge_env_content("", example, {"OPENROUTER_API_KEY": "real-key"})
    assert "OPENROUTER_API_KEY=real-key" in merged
    assert "RAPIDAPI_KEY=your_key_here" in merged  # placeholder for unrelated key preserved


def test_inject_with_openrouter_key_writes_to_env(tmp_path: Path) -> None:
    """The form-field key lands in data/.env as OPENROUTER_API_KEY=..."""
    inject(tmp_path, _MIN_FILES, openrouter_api_key="sk-or-v1-test", skip_smoke_check=True)
    env_content = (tmp_path / "data" / ".env").read_text()
    assert "OPENROUTER_API_KEY=sk-or-v1-test" in env_content


def test_inject_env_file_has_chmod_600(tmp_path: Path) -> None:
    """data/.env is sensitive — must be 0600 after write."""
    import stat as stat_mod

    inject(tmp_path, _MIN_FILES, openrouter_api_key="sk-or-v1-test", skip_smoke_check=True)
    env_path = tmp_path / "data" / ".env"
    mode = env_path.stat().st_mode & 0o777
    assert mode == 0o600, f"expected 0o600, got {stat_mod.filemode(env_path.stat().st_mode)}"


def test_inject_smoke_check_failure_raises_and_skips_sentinel(tmp_path: Path, monkeypatch) -> None:
    """When verify_openrouter_key returns (False, error), inject raises
    OnboardingSmokeCheckFailed and the sentinel is NOT written. Files have
    already been committed (next paste-back will overwrite cleanly)."""
    import findajob.onboarding.injector as inj_mod
    from findajob.onboarding import OnboardingSmokeCheckFailed

    def fake_verify(_key):
        return False, "simulated 401 from OpenRouter"

    monkeypatch.setattr(inj_mod, "verify_openrouter_key", fake_verify)

    with pytest.raises(OnboardingSmokeCheckFailed) as excinfo:
        inject(tmp_path, _MIN_FILES, openrouter_api_key="bad-key")
    assert "simulated 401" in excinfo.value.user_message
    # Files committed; sentinel is NOT
    assert (tmp_path / "candidate_context" / "profile.md").exists()
    assert not (tmp_path / "data" / ".onboarding-complete").exists()


def test_inject_smoke_check_pass_does_not_write_sentinel(tmp_path: Path, monkeypatch) -> None:
    """When verify_openrouter_key returns (True, None), inject() succeeds but
    does NOT write the sentinel. Per #407 the sentinel is deferred to the
    Gmail-config gate's /finish — every onboarding flow ends there."""
    import findajob.onboarding.injector as inj_mod

    def fake_verify(_key):
        return True, None

    monkeypatch.setattr(inj_mod, "verify_openrouter_key", fake_verify)

    inject(tmp_path, _MIN_FILES, openrouter_api_key="sk-or-v1-good")
    assert not (tmp_path / "data" / ".onboarding-complete").exists()


def test_inject_writes_display_name_file(tmp_path: Path) -> None:
    """display_name.txt → candidate_context/display_name.txt (single line)."""
    inject(tmp_path, _MIN_FILES, skip_smoke_check=True)
    assert (tmp_path / "candidate_context" / "display_name.txt").read_text() == "Test Operator"


def test_inject_writes_timezone_file(tmp_path: Path) -> None:
    """timezone.txt → data/timezone (no extension; matches Unix convention)."""
    inject(tmp_path, _MIN_FILES, skip_smoke_check=True)
    assert (tmp_path / "data" / "timezone").read_text() == "America/Los_Angeles"


def test_inject_ntfy_topic_strips_key_prefix(tmp_path: Path) -> None:
    """Body 'NTFY_TOPIC=foo-bar' yields just 'foo-bar' in data/.env."""
    files = {**_MIN_FILES, "ntfy_topic.txt": "NTFY_TOPIC=judy-jobsearch-2026-17"}
    inject(tmp_path, files, skip_smoke_check=True)
    env_content = (tmp_path / "data" / ".env").read_text()
    assert "NTFY_TOPIC=judy-jobsearch-2026-17" in env_content
    # No nested NTFY_TOPIC=NTFY_TOPIC=... shape
    assert "NTFY_TOPIC=NTFY_TOPIC" not in env_content


def test_inject_ntfy_topic_accepts_bare_value(tmp_path: Path) -> None:
    """Body 'just-the-topic' (no KEY= prefix) works too."""
    files = {**_MIN_FILES, "ntfy_topic.txt": "judy-jobsearch-2026-17"}
    inject(tmp_path, files, skip_smoke_check=True)
    env_content = (tmp_path / "data" / ".env").read_text()
    assert "NTFY_TOPIC=judy-jobsearch-2026-17" in env_content


def test_inject_ntfy_topic_empty_body_raises(tmp_path: Path) -> None:
    """An empty ntfy_topic.txt fails loudly rather than silently writing nothing."""
    files = {**_MIN_FILES, "ntfy_topic.txt": "   \n  \n"}
    with pytest.raises(ValueError, match="ntfy_topic"):
        inject(tmp_path, files, skip_smoke_check=True)


def test_inject_preserves_other_env_keys(tmp_path: Path) -> None:
    """A pre-existing .env (with RAPIDAPI_KEY etc.) is preserved across the merge."""
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    (data_dir / ".env").write_text(
        "OPENROUTER_API_KEY=old-shared-key\nRAPIDAPI_KEY=preserve-me\nGOOGLE_API_KEY=preserve-me-too\n"
    )
    inject(tmp_path, _MIN_FILES, openrouter_api_key="user-own-key", skip_smoke_check=True)
    env_content = (data_dir / ".env").read_text()
    assert "OPENROUTER_API_KEY=user-own-key" in env_content
    assert "old-shared-key" not in env_content
    assert "RAPIDAPI_KEY=preserve-me" in env_content
    # GOOGLE_API_KEY from the existing .env must be preserved by merge_env_content.
    assert "GOOGLE_API_KEY=preserve-me-too" in env_content


# ── #339: per-tester RapidAPI key injection ───────────────────────────────────

# Minimal .env.example content that mirrors the real file's key ordering.
# Tests that verify "placeholder preserved" must seed this into tmp_path so
# that merge_env_content() can use the template as its starting base.
_ENV_EXAMPLE_CONTENT = "OPENROUTER_API_KEY=your_key_here\nRAPIDAPI_KEY=your_key_here\nNTFY_TOPIC=your-ntfy-topic\n"


def _seed_env_example(base: Path) -> None:
    """Write a minimal .env.example into tmp_path/data/ for placeholder-preservation tests."""
    (base / "data").mkdir(parents=True, exist_ok=True)
    (base / "data" / ".env.example").write_text(_ENV_EXAMPLE_CONTENT, encoding="utf-8")


def test_inject_both_keys_merged_in_env_example_order(tmp_path: Path) -> None:
    """Both keys provided → env contains both with the new values.

    Order in the merged output follows .env.example: OPENROUTER_API_KEY
    (line 1), then RAPIDAPI_KEY (line 2).
    """
    inject(
        tmp_path,
        _MIN_FILES,
        openrouter_api_key="sk-or-v1-fake-test",
        rapidapi_key="fakeRapidApiTestKey",
        skip_smoke_check=True,
    )
    env_content = (tmp_path / "data" / ".env").read_text()
    assert "OPENROUTER_API_KEY=sk-or-v1-fake-test" in env_content
    assert "RAPIDAPI_KEY=fakeRapidApiTestKey" in env_content
    or_pos = env_content.index("OPENROUTER_API_KEY=sk-or-v1-fake-test")
    rapid_pos = env_content.index("RAPIDAPI_KEY=fakeRapidApiTestKey")
    assert or_pos < rapid_pos, f"Expected OPENROUTER < RAPIDAPI in merged env, got positions {or_pos}, {rapid_pos}"


def test_inject_openrouter_only_leaves_rapidapi_as_placeholder(tmp_path: Path) -> None:
    """OpenRouter only (RapidAPI blank) → only OPENROUTER_API_KEY updated;
    RAPIDAPI_KEY stays at its .env.example placeholder value."""
    _seed_env_example(tmp_path)
    inject(
        tmp_path,
        _MIN_FILES,
        openrouter_api_key="sk-or-v1-fake-test",
        rapidapi_key="",
        skip_smoke_check=True,
    )
    env_content = (tmp_path / "data" / ".env").read_text()
    assert "OPENROUTER_API_KEY=sk-or-v1-fake-test" in env_content
    assert "RAPIDAPI_KEY=your_key_here" in env_content
    # No accidental blank-value writes
    assert "RAPIDAPI_KEY=\n" not in env_content


def test_inject_both_blank_env_unchanged_from_example(tmp_path: Path) -> None:
    """Both blank → no env_updates produced; merged env equals .env.example
    content (modulo NTFY_TOPIC which comes from captured blocks in _MIN_FILES)."""
    _seed_env_example(tmp_path)
    inject(
        tmp_path,
        _MIN_FILES,
        openrouter_api_key="",
        rapidapi_key="",
        skip_smoke_check=True,
    )
    env_content = (tmp_path / "data" / ".env").read_text()
    # Placeholder values preserved for both API keys
    assert "OPENROUTER_API_KEY=your_key_here" in env_content
    assert "RAPIDAPI_KEY=your_key_here" in env_content
    # NTFY_TOPIC from _MIN_FILES emission is still merged
    assert "NTFY_TOPIC=tester-jobsearch-2026-17" in env_content


def test_inject_whitespace_only_rapidapi_treated_as_blank(tmp_path: Path) -> None:
    """Whitespace-only RapidAPI input → treated as blank, not written."""
    _seed_env_example(tmp_path)
    inject(
        tmp_path,
        _MIN_FILES,
        openrouter_api_key="sk-or-v1-fake-test",
        rapidapi_key="   ",
        skip_smoke_check=True,
    )
    env_content = (tmp_path / "data" / ".env").read_text()
    assert "OPENROUTER_API_KEY=sk-or-v1-fake-test" in env_content
    # Whitespace-only value → placeholder preserved
    assert "RAPIDAPI_KEY=your_key_here" in env_content


# ── #283: new OPTIONAL destinations (feed-urls.txt, linkedin-alerts.md) ─────


def test_inject_writes_feed_urls_when_present(tmp_path: Path) -> None:
    """#283 Section B: feed-urls.txt → config/feed_urls.txt (hyphen→underscore)."""
    found = _minimal_found_dict()
    found["feed-urls.txt"] = (
        "https://boards.greenhouse.io/acme\nhttps://jobs.lever.co/example\nhttps://jobs.ashbyhq.com/example-startup\n"
    )
    inject(tmp_path, found, openrouter_api_key="sk-test", skip_smoke_check=True)
    feed_path = tmp_path / "config" / "feed_urls.txt"
    assert feed_path.is_file()
    assert "boards.greenhouse.io/acme" in feed_path.read_text()
    assert "jobs.lever.co/example" in feed_path.read_text()
    assert "jobs.ashbyhq.com/example-startup" in feed_path.read_text()


def test_inject_writes_linkedin_alerts_when_present(tmp_path: Path) -> None:
    """#283 Section C: linkedin-alerts.md → candidate_context/linkedin-alerts.md."""
    found = _minimal_found_dict()
    found["linkedin-alerts.md"] = "# LinkedIn alerts\n- [ ] Step 1\n"
    inject(tmp_path, found, openrouter_api_key="sk-test", skip_smoke_check=True)
    alerts_path = tmp_path / "candidate_context" / "linkedin-alerts.md"
    assert alerts_path.is_file()
    assert "LinkedIn alerts" in alerts_path.read_text()


def test_inject_manual_only_path_emits_no_optional_source_config(tmp_path: Path) -> None:
    """#283: candidate picks 'none' (manual only) → no jsearch/feed-urls/linkedin-alerts emitted."""
    found = _minimal_found_dict()
    # No jsearch_queries.txt, no feed-urls.txt, no linkedin-alerts.md
    inject(tmp_path, found, openrouter_api_key="sk-test", skip_smoke_check=True)
    # Sentinel deferred to gmail-config gate (#407); ALLOWED files committed;
    # no optional source-config files written.
    assert not (tmp_path / "data" / ".onboarding-complete").exists()
    assert not (tmp_path / "config" / "jsearch_queries.txt").is_file()
    assert not (tmp_path / "config" / "feed_urls.txt").is_file()
    assert not (tmp_path / "candidate_context" / "linkedin-alerts.md").is_file()


def test_inject_backs_up_existing_feed_urls_before_overwrite(tmp_path: Path) -> None:
    """#283: re-onboarding via ?mode=rerun backs up existing config/feed_urls.txt."""
    feed_path = tmp_path / "config" / "feed_urls.txt"
    feed_path.parent.mkdir(parents=True, exist_ok=True)
    feed_path.write_text("https://boards.greenhouse.io/oldcompany\n")
    found = _minimal_found_dict()
    found["feed-urls.txt"] = "https://boards.greenhouse.io/newcompany\n"
    result = inject(tmp_path, found, openrouter_api_key="sk-test", skip_smoke_check=True)
    # New content committed
    assert "newcompany" in feed_path.read_text()
    # Old content backed up
    backup_files = list(result.backup_dir.rglob("feed_urls.txt"))
    assert len(backup_files) == 1
    assert "oldcompany" in backup_files[0].read_text()


def test_inject_rollback_includes_tempfile_when_write_fails_mid_staging(tmp_path: Path, monkeypatch) -> None:
    """#215 Fix 1: rollback must clean up tempfiles even if os.fdopen/write
    raises after mkstemp succeeded but before tempfiles.append."""
    import os

    found = _minimal_found_dict()

    # Patch os.fdopen to raise on the THIRD call (after first 2 staging writes succeed).
    real_fdopen = os.fdopen
    call_count = {"n": 0}

    def fail_third(*args, **kwargs):
        call_count["n"] += 1
        if call_count["n"] == 3:
            raise OSError("simulated mid-staging write failure")
        return real_fdopen(*args, **kwargs)

    monkeypatch.setattr(os, "fdopen", fail_third)

    with pytest.raises(OSError):
        inject(tmp_path, found, openrouter_api_key="sk-test", skip_smoke_check=True)

    # The third tempfile was created on disk by mkstemp before fdopen failed.
    # Rollback must have cleaned it up regardless.
    leftover = list(tmp_path.rglob("*.tmp"))
    assert leftover == [], f"rollback left tempfile residue: {leftover}"
