"""Unit tests for #283 emission-consistency warnings.

These warnings are non-blocking — they log to logs/pipeline.jsonl as
event=onboarding_emission_anomaly so prompt-revision regressions can
be spotted in pipeline logs without failing onboarding.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from findajob.onboarding.injector import inject
from tests.test_onboarding_injector import _minimal_found_dict


@pytest.fixture(autouse=True)
def _patch_log_path(tmp_path: Path, monkeypatch):
    """Force findajob.audit.log_event to write to tmp_path/logs/pipeline.jsonl.

    LOG_PATH is resolved at module-import time from findajob.paths.BASE, so
    we patch findajob.audit.LOG_PATH directly — the only reference log_event
    actually reads at call time.
    """
    monkeypatch.setattr(
        "findajob.audit.LOG_PATH",
        str(tmp_path / "logs" / "pipeline.jsonl"),
    )
    yield


def _read_pipeline_events(base: Path) -> list[dict]:
    log = base / "logs" / "pipeline.jsonl"
    if not log.is_file():
        return []
    return [json.loads(line) for line in log.read_text().splitlines() if line.strip()]


def test_warning_when_linkedin_alerts_present_without_jsearch_queries(tmp_path: Path) -> None:
    """linkedin-alerts.md cross-references config/jsearch_queries.txt by path —
    if alerts are emitted but queries are not, the cross-reference is broken."""
    found = _minimal_found_dict()
    found["linkedin-alerts.md"] = "# Alerts\nSee config/jsearch_queries.txt\n"
    # Deliberately omit jsearch_queries.txt
    inject(tmp_path, found, openrouter_api_key="sk-test", skip_smoke_check=True)
    events = _read_pipeline_events(tmp_path)
    anomaly = [e for e in events if e.get("event") == "onboarding_emission_anomaly"]
    assert len(anomaly) >= 1
    assert any("linkedin_alerts_without_jsearch_queries" in e.get("kind", "") for e in anomaly)


def test_warning_when_jsearch_queries_emitted_empty(tmp_path: Path) -> None:
    """An empty jsearch_queries.txt (zero query lines after comment-stripping)
    signals prompt-LLM drift — emit warning."""
    found = _minimal_found_dict()
    found["jsearch_queries.txt"] = "# Generated by findajob\n# 3-4 word queries\n"
    inject(tmp_path, found, openrouter_api_key="sk-test", skip_smoke_check=True)
    events = _read_pipeline_events(tmp_path)
    anomaly = [e for e in events if e.get("event") == "onboarding_emission_anomaly"]
    assert any("jsearch_queries_empty" in e.get("kind", "") for e in anomaly)


def test_no_warning_when_both_present_and_nonempty(tmp_path: Path) -> None:
    """Healthy emission: linkedin-alerts.md + jsearch_queries.txt both present, queries non-empty."""
    found = _minimal_found_dict()
    found["jsearch_queries.txt"] = "# Generated\nsenior backend engineer\nplatform engineer\n"
    found["linkedin-alerts.md"] = "# Alerts\nSee queries above\n"
    inject(tmp_path, found, openrouter_api_key="sk-test", skip_smoke_check=True)
    events = _read_pipeline_events(tmp_path)
    anomaly = [e for e in events if e.get("event") == "onboarding_emission_anomaly"]
    assert anomaly == []
