"""Unit tests for the onboarding injector (#148)."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from unittest.mock import patch

import pytest

from findajob.onboarding.injector import (
    _ALL_DESTINATIONS,
    _COMPANIES_OF_INTEREST_DEST,
    _SENTINEL_RELPATH,
    backup_existing,
    derive_companies_of_interest,
    inject,
    is_complete,
    mark_complete,
)

_MIN_FILES = {
    "profile.md": "# Profile\n",
    "master_resume.md": "# Resume\n",
    "target_companies.md": (
        "# Generated by findajob onboarding interviewer v2 — 2026-04-20\n\n"
        "## Tier 1 — Active Focus\n"
        "- Acme Corp\n"
        "- Example Industries — would take a role there today\n"
        "- Sample Systems (public benefit corp)\n\n"
        "## Tier 2 — Strong Interest\n"
        "- Other Co\n\n"
        "## Notes\n"
        "These are hypothetical.\n"
    ),
    "business_sector_employers_reference.md": "## Categories\n",
    "jsearch_queries.txt": "senior backend engineer\n",
    "prefilter_rules.yaml": "hard_rejects:\n  spam:\n    - '\\bspam\\b'\n",
    "in_domain_patterns.yaml": "positive:\n  - '\\bbackend\\b'\n",
}


def test_all_destinations_map_seven_filenames(tmp_path: Path) -> None:
    assert set(_ALL_DESTINATIONS.keys()) == set(_MIN_FILES.keys())


def test_sentinel_and_companies_paths_are_stable() -> None:
    assert _SENTINEL_RELPATH == "data/.onboarding-complete"
    assert _COMPANIES_OF_INTEREST_DEST == "config/companies_of_interest.txt"


# ---- derive_companies_of_interest ----------------------------------------


def test_derive_tier1_strips_bullets_and_commentary() -> None:
    out = derive_companies_of_interest(_MIN_FILES["target_companies.md"])
    lines = [line for line in out.splitlines() if line]
    assert lines == ["Acme Corp", "Example Industries", "Sample Systems"]


def test_derive_ignores_tier2_and_beyond() -> None:
    md = (
        "## Tier 1 — Active Focus\n- A\n- B\n\n"
        "## Tier 2 — Strong Interest\n- C\n- D\n\n"
        "## Tier 3 — Opportunistic\n- E\n"
    )
    out = derive_companies_of_interest(md)
    assert out.splitlines() == ["A", "B"]


def test_derive_handles_star_bullets_and_numbered() -> None:
    md = "## Tier 1 — Active Focus\n* Alpha Co\n1. Beta Inc\n- Gamma LLC\n"
    out = derive_companies_of_interest(md)
    assert out.splitlines() == ["Alpha Co", "Beta Inc", "Gamma LLC"]


def test_derive_ends_with_newline() -> None:
    out = derive_companies_of_interest("## Tier 1\n- X\n")
    assert out.endswith("\n")


def test_derive_empty_when_no_tier1() -> None:
    assert derive_companies_of_interest("## Tier 2\n- Z\n") == ""


# ---- is_complete / mark_complete -----------------------------------------


def test_is_complete_false_on_empty_base(tmp_path: Path) -> None:
    assert is_complete(tmp_path) is False


def test_mark_and_is_complete_roundtrip(tmp_path: Path) -> None:
    mark_complete(tmp_path)
    assert is_complete(tmp_path) is True
    sentinel = tmp_path / "data" / ".onboarding-complete"
    assert sentinel.is_file()
    content = sentinel.read_text(encoding="utf-8").strip()
    # Parseable ISO 8601 UTC
    parsed = datetime.strptime(content, "%Y-%m-%dT%H:%M:%SZ")
    assert parsed.tzinfo is None  # naive from strptime; our write used Z


# ---- backup_existing ------------------------------------------------------


def test_backup_on_empty_base_creates_empty_dir(tmp_path: Path) -> None:
    dest = backup_existing(tmp_path, "20260423T120000Z")
    assert dest == tmp_path / ".backups" / "20260423T120000Z"
    assert dest.is_dir()
    assert list(dest.rglob("*")) == []


def test_backup_copies_existing_destinations(tmp_path: Path) -> None:
    (tmp_path / "candidate_context").mkdir()
    (tmp_path / "candidate_context" / "profile.md").write_text("old profile\n")
    (tmp_path / "config").mkdir()
    (tmp_path / "config" / "prefilter_rules.yaml").write_text("hard_rejects: {}\n")
    (tmp_path / "data").mkdir()
    (tmp_path / "data" / ".onboarding-complete").write_text("2026-01-01T00:00:00Z\n")

    dest = backup_existing(tmp_path, "20260423T120000Z")
    assert (dest / "candidate_context" / "profile.md").read_text() == "old profile\n"
    assert (dest / "config" / "prefilter_rules.yaml").read_text() == "hard_rejects: {}\n"
    assert (dest / "data" / ".onboarding-complete").read_text() == "2026-01-01T00:00:00Z\n"


# ---- inject ---------------------------------------------------------------


def test_inject_writes_seven_files_and_sentinel_and_derivation(tmp_path: Path) -> None:
    backup = inject(tmp_path, _MIN_FILES)
    assert backup is not None  # returns the (possibly empty) backup dir
    # Seven canonical files
    assert (tmp_path / "candidate_context" / "profile.md").read_text() == _MIN_FILES["profile.md"]
    assert (tmp_path / "candidate_context" / "master_resume.md").read_text() == _MIN_FILES["master_resume.md"]
    assert (tmp_path / "config" / "target_companies.md").read_text() == _MIN_FILES["target_companies.md"]
    assert (tmp_path / "config" / "business_sector_employers_reference.md").read_text() == _MIN_FILES[
        "business_sector_employers_reference.md"
    ]
    assert (tmp_path / "config" / "jsearch_queries.txt").read_text() == _MIN_FILES["jsearch_queries.txt"]
    assert (tmp_path / "config" / "prefilter_rules.yaml").read_text() == _MIN_FILES["prefilter_rules.yaml"]
    assert (tmp_path / "config" / "in_domain_patterns.yaml").read_text() == _MIN_FILES["in_domain_patterns.yaml"]
    # Derived companies_of_interest
    coi = (tmp_path / "config" / "companies_of_interest.txt").read_text()
    assert "Acme Corp" in coi
    assert "Example Industries" in coi
    # Sentinel
    sentinel = tmp_path / "data" / ".onboarding-complete"
    assert sentinel.is_file()


def test_inject_staging_failure_rolls_back(tmp_path: Path) -> None:
    """If staging (tempfile write) fails, no existing files are mutated and
    no partial backup remains.

    We simulate by making ``tempfile.mkstemp`` raise on its 3rd call. Inject
    must propagate, and leave the pre-existing file untouched with no
    tempfile residue and no backup directory.
    """
    # Pre-existing state — must survive the failed inject
    (tmp_path / "candidate_context").mkdir()
    (tmp_path / "candidate_context" / "profile.md").write_text("pre-existing\n")
    original = (tmp_path / "candidate_context" / "profile.md").read_text()

    import findajob.onboarding.injector as inj_mod

    calls = {"n": 0}
    real_mkstemp = inj_mod.tempfile.mkstemp

    def flaky_mkstemp(*args, **kwargs):
        calls["n"] += 1
        if calls["n"] == 3:
            raise OSError("simulated disk full")
        return real_mkstemp(*args, **kwargs)

    with patch.object(inj_mod.tempfile, "mkstemp", side_effect=flaky_mkstemp):
        with pytest.raises(OSError):
            inject(tmp_path, _MIN_FILES)

    # profile.md unchanged
    assert (tmp_path / "candidate_context" / "profile.md").read_text() == original
    # No sentinel
    assert not (tmp_path / "data" / ".onboarding-complete").exists()
    # No derived file
    assert not (tmp_path / "config" / "companies_of_interest.txt").exists()
    # No residual tempfiles
    residual = list((tmp_path / "candidate_context").glob("profile.md.*.tmp"))
    assert residual == []
    # No backup dir left behind
    backups = tmp_path / ".backups"
    assert not backups.exists() or not any(backups.iterdir())


def test_inject_creates_parent_dirs(tmp_path: Path) -> None:
    # Fresh base with no subdirs — inject must mkdir them
    inject(tmp_path, _MIN_FILES)
    assert (tmp_path / "candidate_context").is_dir()
    assert (tmp_path / "config").is_dir()
    assert (tmp_path / "data").is_dir()


def test_inject_raises_on_missing_file_in_parsed(tmp_path: Path) -> None:
    partial = {k: v for k, v in _MIN_FILES.items() if k != "profile.md"}
    with pytest.raises(ValueError, match="profile.md"):
        inject(tmp_path, partial)
