"""Materials viewer routes: /, /materials/{fp}, /materials/{fp}/{file}."""

from __future__ import annotations

import re
import sqlite3
from datetime import UTC, datetime
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, PlainTextResponse, RedirectResponse

from findajob.web.folder_resolver import resolve_folder
from findajob.web.markdown import render_markdown

router = APIRouter()


# Document-type classification for the materials folder view. Filename
# patterns generated by prep_application.py / find_contacts.py / triage.py:
#   "JD - {Company} - {Title}.txt"             — Job Description
#   "Review Checklist - {Company} - {Title}.md"
#   "{Display} Briefing - {Company} - {Title} - {ts}.{md,docx}"
#   "{Display} Resume - {Company} - {Title} - {ts}.{md,docx}"
#   "{Display} Resume Changes - {Company} - {Title} - {ts}.md"
#   "{Display} Cover - {Company} - {Title} - {ts}.{md,docx}"
#   "{Display} Critique - {Company} - {Title} - {ts}.md"
#   "{Display} Outreach to {Recipient} - {Company} - {ts}.txt"
#   "briefing.md"                              — speculative submission folder
# The classifier checks substrings rather than parsing the full pattern so
# changes to display_name / company / title don't break grouping.
_GROUP_RULES: list[tuple[str, str, int]] = [
    # (substring/marker, label, sort order)
    ("JD - ", "Job Description", 1),
    ("briefing.md", "Briefing (speculative)", 2),
    (" Briefing - ", "Briefing", 2),
    (" Resume Changes - ", "Resume Changes", 4),
    (" Resume - ", "Resume", 3),
    (" Cover - ", "Cover Letter", 5),
    (" Outreach to ", "Outreach", 6),
    (" Critique - ", "Recruiter Critique", 7),
    ("Review Checklist - ", "Review Checklist", 8),
]
_OTHER_LABEL = "Other"
_OTHER_ORDER = 99
_OUTREACH_RECIPIENT_RE = re.compile(r" Outreach to ([^-]+?) - ")

# Plain-language explanation per group: what it is + when to use it. Templates
# interpolate {title}, {company}, {recipient} where applicable. Goal is to be
# specific enough that a non-power-user (a beta tester opening this folder for
# the first time) understands which docs are submission artifacts vs internal
# prep notes — the latter must NEVER read as "send this to the employer."
_GROUP_DESCRIPTIONS: dict[str, str] = {
    "Job Description": "The original posting text. Reference while you tailor — not something you send back.",
    "Briefing": (
        "Plain-language brief on {company}, the {title} role, and how your background lines up. "
        "Read first — it informs the resume, cover letter, and interview prep. For your eyes only."
    ),
    "Briefing (speculative)": (
        "Deep-research brief on {company} for cold outreach. Use as the source for the outreach drafts "
        "and any conversations you start. Not something you send."
    ),
    "Resume": "Your resume tailored to {title} at {company}. The .docx is what you submit with the application.",
    "Resume Changes": (
        "Diff-style explanation of how the tailored resume differs from your master resume — "
        "a sanity check so you know what was emphasized or trimmed before you submit. For your eyes only."
    ),
    "Cover Letter": "Cover letter drafted for {title} at {company}. The .docx is what you submit with the application.",
    "Outreach": (
        "Short cold-outreach drafts for people who can refer you or surface the role internally. "
        "Paste into LinkedIn DM or email."
    ),
    "Recruiter Critique": (
        "A simulated recruiter's red-team take on the tailored resume and cover. Read it as a "
        "'what would a skeptic pick on' pass before submitting. For your eyes only."
    ),
    "Review Checklist": (
        "Pre-flight checklist of things to verify before you submit — formatting, claims, contact info."
    ),
}

# Per-(group, ext) one-liner shown on each file row. Tells the user what to
# *do with this specific file* — distinct from the group description above
# which tells them what the doc *is*. Empty string means "fall back to the
# generic ext blurb in the template."
_FILE_HINTS: dict[tuple[str, str], str] = {
    ("Resume", "docx"): "MS Word — submit this with the application",
    ("Resume", "md"): "Markdown source — preview in browser, or Copy MD into Google Docs",
    ("Cover Letter", "docx"): "MS Word — submit this with the application",
    ("Cover Letter", "md"): "Markdown source — preview in browser, or Copy MD into Google Docs",
    ("Briefing", "docx"): "MS Word — printable copy of the briefing",
    ("Briefing", "md"): "Markdown source — preview in browser",
    ("Briefing (speculative)", "md"): "Markdown source — preview in browser",
    ("Outreach", "txt"): "Plain text — paste into LinkedIn DM or email",
    ("Job Description", "txt"): "Plain text — the original posting",
    ("Resume Changes", "md"): "Markdown source — preview in browser",
    ("Recruiter Critique", "md"): "Markdown source — preview in browser",
    ("Review Checklist", "md"): "Markdown source — preview in browser",
}


def _classify_file(name: str) -> tuple[str, int]:
    """Return (group label, sort order) for a filename. Falls back to 'Other'."""
    if name == "briefing.md":
        return ("Briefing (speculative)", 2)
    for marker, label, order in _GROUP_RULES:
        if marker in name:
            return (label, order)
    return (_OTHER_LABEL, _OTHER_ORDER)


def _human_size(n: int) -> str:
    """Compact size for the UI: B / K / M only — folders never reach G."""
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n // 1024} K"
    return f"{n // (1024 * 1024)} M"


def _human_mtime(ts: float) -> str:
    """Render an mtime as 'YYYY-MM-DD HH:MM' UTC for stable comparison across
    container TZs. Operator + testers all read this in their browser TZ via
    the fact it shows the same UTC clock; precise relative time isn't worth
    the JS dependency."""
    return datetime.fromtimestamp(ts, tz=UTC).strftime("%Y-%m-%d %H:%M UTC")


def _format_description(label: str, title: str, company: str) -> str:
    """Render the group description with title/company interpolated. Falls
    back to empty string if no description is registered (e.g. 'Other')."""
    template = _GROUP_DESCRIPTIONS.get(label, "")
    if not template:
        return ""
    return template.format(title=title or "this role", company=company or "this company")


def _group_files(folder: Path, title: str = "", company: str = "") -> list[dict]:
    """Group files in a prep folder by document type, ordered for the
    natural reading sequence (JD first, Review Checklist last). Each group
    carries a plain-language description; each file row carries a
    per-(group, ext) hint plus its display affordance — .md/.txt render
    inline (View), everything else downloads (Download)."""
    by_label: dict[str, dict] = {}
    for p in sorted(folder.iterdir()):
        if not p.is_file():
            continue
        label, order = _classify_file(p.name)
        ext = p.suffix.lower().lstrip(".")
        # .md and .txt render inline via the file_serve route; .docx and
        # everything else are forced downloads (Content-Disposition: attachment).
        is_view = ext in ("md", "txt")
        recipient = None
        if " Outreach to " in p.name:
            m = _OUTREACH_RECIPIENT_RE.search(p.name)
            if m:
                recipient = m.group(1).strip()
        try:
            stat = p.stat()
            size = _human_size(stat.st_size)
            mtime = _human_mtime(stat.st_mtime)
        except OSError:
            size = ""
            mtime = ""
        entry = {
            "name": p.name,
            "ext": ext,
            "is_view": is_view,
            "recipient": recipient,
            "size": size,
            "mtime": mtime,
            "hint": _FILE_HINTS.get((label, ext), ""),
        }
        by_label.setdefault(
            label,
            {
                "label": label,
                "order": order,
                "description": _format_description(label, title, company),
                "files": [],
            },
        )
        by_label[label]["files"].append(entry)

    # Within each group, order: .md first (View), then .txt (View),
    # then .docx (Download), then anything else.
    ext_priority = {"md": 0, "txt": 1, "docx": 2}
    for g in by_label.values():
        g["files"].sort(key=lambda f: (ext_priority.get(f["ext"], 99), f["name"]))

    return sorted(by_label.values(), key=lambda g: (g["order"], g["label"]))


def get_db() -> sqlite3.Connection:  # pragma: no cover — overridden in app factory
    raise NotImplementedError("DB dependency must be overridden by create_app()")


_INDEX_QUERY_SECTIONS = [
    ("In flight", "stage IN ('materials_drafted', 'prep_in_progress')", "created_at DESC"),
    ("Applied", "stage IN ('applied', 'interview', 'offer')", "COALESCE(stage_updated, created_at) DESC"),
    ("Waitlisted", "stage = 'waitlisted'", "created_at DESC"),
]
_REJECTED_CLAUSE = "stage IN ('rejected', 'not_selected')"
_PER_SECTION_CAP = 50


def _fetch_section(db: sqlite3.Connection, where: str, order: str) -> list[sqlite3.Row]:
    return db.execute(
        f"SELECT fingerprint, title, company, stage, fit_score, created_at, stage_updated "
        f"FROM jobs WHERE {where} ORDER BY {order} LIMIT {_PER_SECTION_CAP + 1}"
    ).fetchall()


@router.get("/materials/", response_class=HTMLResponse)
def materials_index(request: Request, db: sqlite3.Connection = Depends(get_db)) -> HTMLResponse:  # noqa: B008
    sections = []
    for name, where, order in _INDEX_QUERY_SECTIONS:
        rows = _fetch_section(db, where, order)
        overflow = len(rows) > _PER_SECTION_CAP
        sections.append({"name": name, "rows": rows[:_PER_SECTION_CAP], "overflow": overflow})
    rejected_rows = _fetch_section(db, _REJECTED_CLAUSE, "created_at DESC")
    rejected = {
        "rows": rejected_rows[:_PER_SECTION_CAP],
        "overflow": len(rejected_rows) > _PER_SECTION_CAP,
        "count": len(rejected_rows) if len(rejected_rows) <= _PER_SECTION_CAP else f"{_PER_SECTION_CAP}+",
    }
    templates = request.app.state.templates
    return templates.TemplateResponse(
        request=request,
        name="materials/index.html",
        context={"sections": sections, "rejected": rejected},
    )


@router.get("/materials/{fingerprint}", response_class=HTMLResponse, response_model=None)
def folder_view(
    fingerprint: str,
    request: Request,
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> HTMLResponse | RedirectResponse:
    from findajob.cost_rollups import per_job_breakdown

    root: Path = request.app.state.companies_root
    folder = resolve_folder(fingerprint, db, root)
    if folder is None:
        # Synthetic rows have no prep folder until flag-for-prep — surface the
        # role-card description (raw_jd_text) instead of dead-ending.
        synth_row = db.execute("SELECT synthetic FROM jobs WHERE fingerprint = ?", (fingerprint,)).fetchone()
        if synth_row is not None and synth_row["synthetic"]:
            return RedirectResponse(url=f"/jobs/{fingerprint}/jd", status_code=303)
        raise HTTPException(status_code=404, detail="folder not found")
    row = db.execute("SELECT id, title, company, stage FROM jobs WHERE fingerprint = ?", (fingerprint,)).fetchone()
    title = row["title"] if row else ""
    company = row["company"] if row else ""
    groups = _group_files(folder, title=title, company=company)

    # #87 — per-operation cost breakdown (only if cost tables exist; fail open)
    breakdown = []
    breakdown_total = None
    if row is not None:
        try:
            breakdown = per_job_breakdown(db, row["id"])
            if breakdown:
                breakdown_total = sum(r.cost_usd for r in breakdown)
        except sqlite3.OperationalError:
            # Test fixtures or pre-Task-1 stacks may lack cost_log/cost_calibration.
            breakdown = []

    templates = request.app.state.templates
    return templates.TemplateResponse(
        request=request,
        name="materials/folder.html",
        context={
            "fingerprint": fingerprint,
            "folder_name": folder.name,
            "title": title,
            "company": company,
            "stage": row["stage"] if row else "",
            "groups": groups,
            "breakdown": breakdown,
            "breakdown_total": breakdown_total,
        },
    )


@router.get("/jobs/{fingerprint}/jd", response_class=HTMLResponse)
def jd_view(
    fingerprint: str,
    request: Request,
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> HTMLResponse:
    row = db.execute(
        "SELECT title, company, raw_jd_text FROM jobs WHERE fingerprint = ?",
        (fingerprint,),
    ).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="job not found")
    body = (row["raw_jd_text"] or "").strip()
    header = f"# {row['title']}\n\n_{row['company']}_\n\n---\n\n"
    md = header + (body if body else "_No JD text on file._")
    templates = request.app.state.templates
    return templates.TemplateResponse(
        request=request,
        name="base.html",
        context={"_rendered_md": render_markdown(md)},
        headers={"content-type": "text/html; charset=utf-8"},
    )


@router.get("/materials/{fingerprint}/{filename}")
def file_serve(
    fingerprint: str,
    filename: str,
    request: Request,
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
    raw: int = 0,
):
    root: Path = request.app.state.companies_root
    folder = resolve_folder(fingerprint, db, root)
    if folder is None:
        raise HTTPException(status_code=404, detail="folder not found")
    candidate = (folder / filename).resolve()
    try:
        candidate.relative_to(folder.resolve())
    except ValueError:
        raise HTTPException(status_code=404, detail="invalid filename") from None
    if not candidate.is_file():
        raise HTTPException(status_code=404, detail="file not found")
    ext = candidate.suffix.lower()
    # ?raw=1 returns the .md / .txt source bytes verbatim — used by the
    # "Copy MD" button on the folder page so what lands on the clipboard
    # is byte-identical to the file on disk (no markdown→HTML→back-to-text
    # round-trip via the rendered prose view).
    if raw and ext in (".md", ".txt"):
        return PlainTextResponse(content=candidate.read_text(encoding="utf-8", errors="replace"))
    if ext == ".md":
        body = candidate.read_text(encoding="utf-8", errors="replace")
        templates = request.app.state.templates
        return templates.TemplateResponse(
            request=request,
            name="base.html",
            context={"_rendered_md": render_markdown(body)},
            headers={"content-type": "text/html; charset=utf-8"},
        )
    if ext == ".txt":
        return PlainTextResponse(content=candidate.read_text(encoding="utf-8", errors="replace"))
    return FileResponse(
        path=candidate,
        filename=candidate.name,
        media_type="application/octet-stream",
        headers={"content-disposition": f'attachment; filename="{candidate.name}"'},
    )
