"""Materials viewer + editor routes.

GET routes:
  /materials/                              — index across In flight / Applied / Waitlisted / Rejected sections
  /materials/{fp}                          — per-job folder view (with post-applied banner #210)
  /materials/{fp}/{file}                   — inline render for .md/.txt, blob download for binaries

POST routes:
  /materials/{fp}/regenerate               — full LLM re-run (delegates to prep subprocess; #616)
  /materials/{fp}/rerun-interview-prep     — re-run interview prep only for interview-stage jobs (#875)
  /materials/{fp}/files/{filename}         — atomic edit-and-save for .md files; auto-regenerates .docx sibling (#210)
"""

from __future__ import annotations

import json
import os
import re
import shutil
import sqlite3
import subprocess
import tempfile
from datetime import UTC, datetime
from pathlib import Path

from fastapi import APIRouter, Depends, Form, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, PlainTextResponse, RedirectResponse

from findajob.prep.docx_postprocess import _linkify_contact_info
from findajob.prep.docx_render import render_md_to_docx
from findajob.web.folder_resolver import resolve_folder
from findajob.web.markdown import render_markdown

router = APIRouter()


# Document-type classification for the materials folder view. Filename
# patterns generated by prep_application.py / find_contacts.py / triage.py:
#   "JD - {Company} - {Title}.txt"             — Job Description
#   "Review Checklist - {Company} - {Title}.md"
#   "{Display} Briefing - {Company} - {Title} - {ts}.{md,docx}"
#   "{Display} Resume - {Company} - {Title} - {ts}.{md,docx}"
#   "{Display} Resume Changes - {Company} - {Title} - {ts}.md"
#   "{Display} Cover - {Company} - {Title} - {ts}.{md,docx}"
#   "{Display} Critique - {Company} - {Title} - {ts}.md"
#   "{Display} Outreach to {Recipient} - {Company} - {ts}.txt"
#   "briefing.md"                              — speculative submission folder
# The classifier checks substrings rather than parsing the full pattern so
# changes to display_name / company / title don't break grouping.
_GROUP_RULES: list[tuple[str, str, int]] = [
    # (substring/marker, label, sort order)
    ("JD - ", "Job Description", 1),
    ("briefing.md", "Briefing (speculative)", 2),
    (" Briefing - ", "Briefing", 2),
    (" Resume Changes - ", "Resume Changes", 4),
    (" Resume - ", "Resume", 3),
    (" Cover - ", "Cover Letter", 5),
    (" Outreach to ", "Outreach", 6),
    (" Critique - ", "Recruiter Critique", 7),
    ("Review Checklist - ", "Review Checklist", 8),
    (" Interview Prep - ", "Interview Prep", 9),
    (" Study Guide - ", "Study Guide", 10),
    (" Flashcards - ", "Flashcards", 11),
]
_OTHER_LABEL = "Other"
_OTHER_ORDER = 99
_OUTREACH_RECIPIENT_RE = re.compile(r" Outreach to ([^-]+?) - ")
# Hide audit-snapshot (.applied-YYYY-MM-DD.md, written on apply transition #210)
# and edit-backup (.bak, written on first edit via /materials/{fp}/files/{name})
# files from the per-folder view — they exist for audit/recovery, not day-to-day display.
_HIDE_FROM_VIEW_RE = re.compile(
    r"\.applied-\d{4}-\d{2}-\d{2}\.md$|\.bak$| Flashcards - .*\.json$|interview_prep_podcast_.*\.mp3$"
)
_APPLIED_DATE_RE = re.compile(r"\.applied-(\d{4}-\d{2}-\d{2})\.md$")

# Stages where the materials have already been sent — banner reminds the
# operator that edits don't change what the employer received.
POST_APPLIED_STAGES = frozenset({"applied", "interview", "offer", "not_selected", "withdrawn"})

# Briefing-first gate stage (#691). The folder view renders a Continue-prep
# affordance + reject dropdown when stage matches, so the operator can
# decide based on Phase A's briefing before paying for Phase B.
BRIEFING_GATE_STAGE = "briefing_ready"


def _latest_applied_date(folder: Path) -> str | None:
    """Return the most recent date (YYYY-MM-DD) seen in *.applied-DATE.md
    snapshot filenames, or None if no snapshots exist."""
    dates = []
    for p in folder.iterdir():
        if not p.is_file():
            continue
        m = _APPLIED_DATE_RE.search(p.name)
        if m:
            dates.append(m.group(1))
    return max(dates) if dates else None


# Plain-language explanation per group: what it is + when to use it. Templates
# interpolate {title}, {company}, {recipient} where applicable. Goal is to be
# specific enough that a non-power-user (a user opening this folder for
# the first time) understands which docs are submission artifacts vs internal
# prep notes — the latter must NEVER read as "send this to the employer."
_GROUP_DESCRIPTIONS: dict[str, str] = {
    "Job Description": "The original posting text. Reference while you tailor — not something you send back.",
    "Briefing": (
        "Plain-language brief on {company}, the {title} role, and how your background lines up. "
        "Read first — it informs the resume, cover letter, and interview prep. For your eyes only."
    ),
    "Briefing (speculative)": (
        "Deep-research brief on {company} for cold outreach. Use as the source for the outreach drafts "
        "and any conversations you start. Not something you send."
    ),
    "Resume": "Your resume tailored to {title} at {company}. The .docx is what you submit with the application.",
    "Resume Changes": (
        "Diff-style explanation of how the tailored resume differs from your master resume — "
        "a sanity check so you know what was emphasized or trimmed before you submit. For your eyes only."
    ),
    "Cover Letter": "Cover letter drafted for {title} at {company}. The .docx is what you submit with the application.",
    "Outreach": (
        "Short cold-outreach drafts for people who can refer you or surface the role internally. "
        "Paste into LinkedIn DM or email."
    ),
    "Recruiter Critique": (
        "A simulated recruiter's red-team take on the tailored resume and cover. Read it as a "
        "'what would a skeptic pick on' pass before submitting. For your eyes only."
    ),
    "Review Checklist": (
        "Pre-flight checklist of things to verify before you submit — formatting, claims, contact info."
    ),
    "Interview Prep": (
        "Interview notes for {title} at {company} — STAR stories, questions to ask, tough Qs to anticipate. "
        "Read before each round to anchor your talking points. For your eyes only."
    ),
    "Study Guide": (
        "Condensed study guide for {title} at {company} — key themes, STAR stories, technical deep dives, "
        "company signals, and your elevator pitch. For your eyes only."
    ),
    "Flashcards": (
        "Spaced-repetition flashcard deck for {title} at {company}. "
        "Study in-browser below, or import the .apkg into Anki / .csv into Quizlet."
    ),
}

# Per-(group, ext) one-liner shown on each file row. Tells the user what to
# *do with this specific file* — distinct from the group description above
# which tells them what the doc *is*. Empty string means "fall back to the
# generic ext blurb in the template."
_FILE_HINTS: dict[tuple[str, str], str] = {
    ("Resume", "docx"): "MS Word — submit this with the application",
    ("Resume", "md"): "Markdown source — preview in browser, or Copy MD into Google Docs",
    ("Cover Letter", "docx"): "MS Word — submit this with the application",
    ("Cover Letter", "md"): "Markdown source — preview in browser, or Copy MD into Google Docs",
    ("Briefing", "docx"): "MS Word — printable copy of the briefing",
    ("Briefing", "md"): "Markdown source — preview in browser",
    ("Briefing (speculative)", "md"): "Markdown source — preview in browser",
    ("Outreach", "txt"): "Plain text — paste into LinkedIn DM or email",
    ("Job Description", "txt"): "Plain text — the original posting",
    ("Resume Changes", "md"): "Markdown source — preview in browser",
    ("Recruiter Critique", "md"): "Markdown source — preview in browser",
    ("Review Checklist", "md"): "Markdown source — preview in browser",
    ("Interview Prep", "docx"): "MS Word — printable copy of your interview notes",
    ("Interview Prep", "md"): "Markdown source — preview in browser, or Copy MD into Google Docs",
    ("Study Guide", "md"): "Markdown source — preview in browser, or Copy MD into Google Docs",
    ("Flashcards", "apkg"): "Anki package — import into Anki for spaced-repetition study",
    ("Flashcards", "csv"): "CSV — import into Quizlet or any flashcard app",
}


def _classify_file(name: str) -> tuple[str, int]:
    """Return (group label, sort order) for a filename. Falls back to 'Other'."""
    if name == "briefing.md":
        return ("Briefing (speculative)", 2)
    for marker, label, order in _GROUP_RULES:
        if marker in name:
            return (label, order)
    return (_OTHER_LABEL, _OTHER_ORDER)


def _human_size(n: int) -> str:
    """Compact size for the UI: B / K / M only — folders never reach G."""
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n // 1024} K"
    return f"{n // (1024 * 1024)} M"


def _human_mtime(ts: float) -> str:
    """Render an mtime as 'YYYY-MM-DD HH:MM' UTC for stable comparison across
    container TZs. Operator + testers all read this in their browser TZ via
    the fact it shows the same UTC clock; precise relative time isn't worth
    the JS dependency."""
    return datetime.fromtimestamp(ts, tz=UTC).strftime("%Y-%m-%d %H:%M UTC")


def _format_description(label: str, title: str, company: str) -> str:
    """Render the group description with title/company interpolated. Falls
    back to empty string if no description is registered (e.g. 'Other')."""
    template = _GROUP_DESCRIPTIONS.get(label, "")
    if not template:
        return ""
    return template.format(title=title or "this role", company=company or "this company")


def _group_files(folder: Path, title: str = "", company: str = "") -> list[dict]:
    """Group files in a prep folder by document type, ordered for the
    natural reading sequence (JD first, Review Checklist last). Each group
    carries a plain-language description; each file row carries a
    per-(group, ext) hint plus its display affordance — .md/.txt render
    inline (View), everything else downloads (Download)."""
    by_label: dict[str, dict] = {}
    for p in sorted(folder.iterdir()):
        if not p.is_file():
            continue
        if _HIDE_FROM_VIEW_RE.search(p.name):
            continue
        label, order = _classify_file(p.name)
        ext = p.suffix.lower().lstrip(".")
        # .md and .txt render inline via the file_serve route; .docx and
        # everything else are forced downloads (Content-Disposition: attachment).
        is_view = ext in ("md", "txt")
        recipient = None
        if " Outreach to " in p.name:
            m = _OUTREACH_RECIPIENT_RE.search(p.name)
            if m:
                recipient = m.group(1).strip()
        try:
            stat = p.stat()
            size = _human_size(stat.st_size)
            mtime = _human_mtime(stat.st_mtime)
        except OSError:
            size = ""
            mtime = ""
        entry = {
            "name": p.name,
            "ext": ext,
            "is_view": is_view,
            "recipient": recipient,
            "size": size,
            "mtime": mtime,
            "hint": _FILE_HINTS.get((label, ext), ""),
        }
        by_label.setdefault(
            label,
            {
                "label": label,
                "order": order,
                "description": _format_description(label, title, company),
                "files": [],
            },
        )
        by_label[label]["files"].append(entry)

    # Within each group, order: .md first (View), then .txt (View),
    # then .docx (Download), then anything else.
    ext_priority = {"md": 0, "txt": 1, "docx": 2}
    for g in by_label.values():
        g["files"].sort(key=lambda f: (ext_priority.get(f["ext"], 99), f["name"]))

    return sorted(by_label.values(), key=lambda g: (g["order"], g["label"]))


def get_db() -> sqlite3.Connection:  # pragma: no cover — overridden in app factory
    raise NotImplementedError("DB dependency must be overridden by create_app()")


_INDEX_QUERY_SECTIONS = [
    ("In flight", "stage IN ('materials_drafted', 'prep_in_progress')", "created_at DESC"),
    ("Applied", "stage IN ('applied', 'interview', 'offer')", "COALESCE(stage_updated, created_at) DESC"),
    ("Waitlisted", "stage = 'waitlisted'", "created_at DESC"),
]
_REJECTED_CLAUSE = "stage IN ('rejected', 'not_selected')"
_PER_SECTION_CAP = 50


def _fetch_section(db: sqlite3.Connection, where: str, order: str) -> list[sqlite3.Row]:
    return db.execute(
        f"SELECT fingerprint, title, company, stage, fit_score, created_at, stage_updated "
        f"FROM jobs WHERE {where} ORDER BY {order} LIMIT {_PER_SECTION_CAP + 1}"
    ).fetchall()


@router.get("/materials/", response_class=HTMLResponse)
def materials_index(
    request: Request,
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
    regen_error: str = "",
) -> HTMLResponse:
    sections = []
    for name, where, order in _INDEX_QUERY_SECTIONS:
        rows = _fetch_section(db, where, order)
        overflow = len(rows) > _PER_SECTION_CAP
        sections.append({"name": name, "rows": rows[:_PER_SECTION_CAP], "overflow": overflow})
    rejected_rows = _fetch_section(db, _REJECTED_CLAUSE, "created_at DESC")
    rejected = {
        "rows": rejected_rows[:_PER_SECTION_CAP],
        "overflow": len(rejected_rows) > _PER_SECTION_CAP,
        "count": len(rejected_rows) if len(rejected_rows) <= _PER_SECTION_CAP else f"{_PER_SECTION_CAP}+",
    }
    templates = request.app.state.templates
    return templates.TemplateResponse(
        request=request,
        name="materials/index.html",
        context={"sections": sections, "rejected": rejected, "regen_error": regen_error},
    )


def _resolve_folder_with_speculative_fallback(fingerprint: str, db: sqlite3.Connection, root: Path) -> Path | None:
    """resolve_folder + synthetic-row fallback to speculative_briefing_folder.

    Synthetic rows have no prep_folder_path until flag-for-prep, but the
    speculative briefing folder exists on disk from approve-time. Both the
    folder index and the per-file route need to reach into it; keeping the
    fallback in one place avoids the drift that produced #589 (folder index
    rendered the speculative briefing row, single-file route 404'd).

    Returns None when the row has no usable folder. Callers decide UX:
    folder_view redirects synthetic-no-folder rows to /jd, file_serve 404s.
    """
    folder = resolve_folder(fingerprint, db, root)
    if folder is not None:
        return folder
    synth_row = db.execute(
        "SELECT synthetic, speculative_briefing_folder FROM jobs WHERE fingerprint = ?",
        (fingerprint,),
    ).fetchone()
    if synth_row is None or not synth_row["synthetic"]:
        return None
    spec_folder_name = synth_row["speculative_briefing_folder"]
    if not spec_folder_name:
        return None
    spec_folder = (root / spec_folder_name).resolve()
    try:
        spec_folder.relative_to(root.resolve())
    except ValueError:
        return None  # path-traversal guard on the stored folder name
    if not spec_folder.is_dir():
        return None
    return spec_folder


@router.get("/materials/{fingerprint}", response_class=HTMLResponse, response_model=None)
def folder_view(
    fingerprint: str,
    request: Request,
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> HTMLResponse | RedirectResponse:
    from findajob.cost_rollups import per_job_breakdown

    root: Path = request.app.state.companies_root
    folder = _resolve_folder_with_speculative_fallback(fingerprint, db, root)
    if folder is None:
        # Synthetic rows with no usable briefing folder land on the role-card
        # description page; non-synthetic missing-folder is a 404.
        synth_row = db.execute(
            "SELECT synthetic FROM jobs WHERE fingerprint = ?",
            (fingerprint,),
        ).fetchone()
        if synth_row is not None and synth_row["synthetic"]:
            return RedirectResponse(url=f"/jobs/{fingerprint}/jd", status_code=303)
        raise HTTPException(status_code=404, detail="folder not found")
    row = db.execute(
        "SELECT id, title, company, stage, stage_updated FROM jobs WHERE fingerprint = ?",
        (fingerprint,),
    ).fetchone()
    title = row["title"] if row else ""
    company = row["company"] if row else ""
    groups = _group_files(folder, title=title, company=company)

    # Per-operation cost breakdown (only if cost_log exists; fail open)
    breakdown = []
    breakdown_total = None
    if row is not None:
        try:
            breakdown = per_job_breakdown(db, row["id"])
            if breakdown:
                breakdown_total = sum(r.cost_usd for r in breakdown)
        except sqlite3.OperationalError:
            # Test fixtures may lack cost_log.
            breakdown = []

    stage = row["stage"] if row else ""
    is_post_applied = stage in POST_APPLIED_STAGES
    applied_date = _latest_applied_date(folder) if is_post_applied else None

    # Briefing-first gate (#691). Load reject_reasons only when the gate is
    # active so the folder view stays cheap for the other 99% of states.
    is_briefing_gate = stage == BRIEFING_GATE_STAGE
    reject_reasons: tuple[str, ...] = ()
    if is_briefing_gate:
        from findajob.config_loader import load_reject_reasons

        try:
            reject_reasons, _ = load_reject_reasons()
        except Exception:
            # Missing / malformed yaml: the gate still renders with a
            # free-text reject input via the fallback (handled in template).
            reject_reasons = ()

    # Load flashcard data for the in-browser viewer (latest .json in the folder
    # that matches the Flashcards group pattern). Parsed into a list so Jinja's
    # |tojson filter produces safe, unambiguous output for the Alpine x-data attr.
    flashcards_data: list | None = None
    for p in sorted(folder.iterdir(), key=lambda p: p.stat().st_mtime, reverse=True):
        if p.is_file() and " Flashcards - " in p.name and p.suffix == ".json":
            try:
                flashcards_data = json.loads(p.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                pass
            break

    # Interview prep re-run (#875). Show button when stage=interview;
    # detect in-flight task to disable re-click.
    is_interview_stage = stage == "interview"
    interview_prep_generating = False
    if is_interview_stage and row is not None:
        from findajob.background_tasks import find_active_for_subject

        interview_prep_generating = find_active_for_subject(db, row["id"], "interview_prep") is not None

    # Podcast section (#870). Detect which podcast formats have been generated
    # and build the context for the template's audio player + generate buttons.
    gemini_configured = bool(os.environ.get("GEMINI_API_KEY", "").strip())
    job_id = row["id"] if row else None
    podcast_formats = _build_podcast_context(folder, db=db, job_id=job_id) if gemini_configured else []

    templates = request.app.state.templates
    return templates.TemplateResponse(
        request=request,
        name="materials/folder.html",
        context={
            "fingerprint": fingerprint,
            "folder_name": folder.name,
            "title": title,
            "company": company,
            "stage": stage,
            "last_generated_iso": row["stage_updated"] if row else None,
            "groups": groups,
            "breakdown": breakdown,
            "breakdown_total": breakdown_total,
            "is_post_applied": is_post_applied,
            "applied_date": applied_date,
            "is_briefing_gate": is_briefing_gate,
            "reject_reasons": reject_reasons,
            "is_interview_stage": is_interview_stage,
            "interview_prep_generating": interview_prep_generating,
            "interview_rerun_error": request.query_params.get("interview_rerun_error", ""),
            "flashcards_data": flashcards_data,
            "gemini_configured": gemini_configured,
            "podcast_formats": podcast_formats,
            "podcast_error": request.query_params.get("podcast_error", ""),
        },
    )


_PODCAST_FORMAT_META: dict[str, tuple[str, str]] = {
    "deep_dive": ("Deep Dive", "Two hosts break down the company, role, and interview angles (~8 min)"),
    "deep_dive_long": (
        "Deep Dive (Extended)",
        "Thorough version with more company context and interview prep (~15 min)",
    ),
    "brief": ("The Brief", "Quick summary: strongest angle, biggest gap, key question (~3 min)"),
    "qa_drill": ("Q&A Drill", "Mock interview: realistic questions with coaching on each answer (~8 min)"),
    "critical_analysis": (
        "Critical Analysis",
        "Hiring manager objections and counter-strategies (~8 min)",
    ),
}


def _build_podcast_context(
    folder: Path,
    db: sqlite3.Connection | None = None,
    job_id: str | None = None,
) -> list[dict]:
    """Build template context for the podcast section.

    When ``db`` and ``job_id`` are provided, checks ``background_tasks``
    for a running podcast task and sets ``generating=True`` on all format
    entries — per-job guard means one podcast at a time (#879).
    """
    is_generating = False
    if db is not None and job_id is not None:
        from findajob.background_tasks import find_active_for_subject

        is_generating = find_active_for_subject(db, job_id, "podcast") is not None

    result = []
    for fmt_key, (label, desc) in _PODCAST_FORMAT_META.items():
        filename = f"interview_prep_podcast_{fmt_key}.mp3"
        mp3_path = folder / filename
        exists = mp3_path.is_file()
        entry: dict = {
            "format_key": fmt_key,
            "format_label": label,
            "description": desc,
            "filename": filename,
            "exists": exists,
            "generating": is_generating,
            "size": "",
            "mtime": "",
        }
        if exists:
            stat = mp3_path.stat()
            size_mb = stat.st_size / (1024 * 1024)
            entry["size"] = f"{size_mb:.1f} MB" if size_mb >= 1 else f"{stat.st_size / 1024:.0f} KB"
            entry["mtime"] = datetime.fromtimestamp(stat.st_mtime, tz=UTC).strftime("%Y-%m-%d %H:%M UTC")
        result.append(entry)
    return result


@router.post("/materials/{fingerprint}/podcast/{podcast_format}", response_class=RedirectResponse)
def generate_podcast_from_materials(
    fingerprint: str,
    podcast_format: str,
    request: Request,  # noqa: ARG001
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> RedirectResponse:
    """On-demand podcast generation for any format from the materials page.

    Launches the scriptwriter + TTS pipeline synchronously (typical ~30-60s)
    and redirects back to the materials page. Per-job concurrency guard via
    ``background_tasks`` row; spend ceiling enforced via launch gate +
    per-call gate (two-point pattern).
    """
    from findajob.background_tasks import find_active_for_subject, record_start, writeback_sync
    from findajob.interview.orchestrator import FORMAT_INSTRUCTIONS, generate_podcast_for_job
    from findajob.spend_ceiling import check_launch_gate

    if podcast_format not in FORMAT_INSTRUCTIONS:
        raise HTTPException(status_code=400, detail=f"Unknown podcast format: {podcast_format}")

    job = db.execute(
        "SELECT id, title, company, raw_jd_text, prep_folder_path FROM jobs WHERE fingerprint=?",
        (fingerprint,),
    ).fetchone()
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")

    if find_active_for_subject(db, job["id"], "podcast"):
        return RedirectResponse(
            url=f"/materials/{fingerprint}?podcast_error=already_generating",
            status_code=303,
        )

    prep_folder = job["prep_folder_path"]
    if not prep_folder or not os.path.isdir(prep_folder):
        raise HTTPException(status_code=404, detail="No prep folder")

    refusal = check_launch_gate(db)
    if refusal:
        return RedirectResponse(
            url=f"/materials/{fingerprint}?podcast_error=spend_ceiling",
            status_code=303,
        )

    def _read_latest(pattern: str) -> str:
        folder_path = Path(prep_folder)
        pat = re.compile(pattern)
        matches = sorted(
            (p for p in folder_path.iterdir() if p.is_file() and pat.search(p.name)),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        if not matches:
            return ""
        try:
            return matches[0].read_text(encoding="utf-8")
        except OSError:
            return ""

    briefing = _read_latest(r"Briefing.*\.md$")
    resume = _read_latest(r"(?<!Changes )Resume(?! Changes).*\.md$")
    cover = _read_latest(r"Cover.*\.md$")
    critique = _read_latest(r"Critique.*\.md$")
    interview_prep = _read_latest(r"Interview Prep.*\.md$")

    if not briefing or not interview_prep:
        raise HTTPException(status_code=409, detail="Missing briefing or interview prep artifacts")

    from findajob.paths import BASE

    profile_path = f"{BASE}/candidate_context/profile.md"
    master_path = f"{BASE}/candidate_context/master_resume.md"
    profile = Path(profile_path).read_text(encoding="utf-8") if Path(profile_path).is_file() else ""
    master = Path(master_path).read_text(encoding="utf-8") if Path(master_path).is_file() else ""
    cached_prefix = f"CANDIDATE PROFILE:\n{profile}\n\nMASTER RESUME:\n{master}"

    task_id = record_start(db, job_id=job["id"], kind="podcast")
    try:
        with writeback_sync(db, task_id):
            generate_podcast_for_job(
                prep_folder=prep_folder,
                company=job["company"],
                title=job["title"],
                job_id=job["id"],
                jd_text=job["raw_jd_text"] or "",
                briefing=briefing,
                resume=resume,
                cover=cover,
                critique=critique,
                interview_prep=interview_prep,
                cached_prefix=cached_prefix,
                podcast_format=podcast_format,
                conn=db,
            )
    except Exception as exc:  # noqa: BLE001
        from findajob.audit import log_event

        log_event(
            "podcast_on_demand_error",
            fingerprint=fingerprint,
            format=podcast_format,
            error=f"{type(exc).__name__}: {exc}",
        )
        return RedirectResponse(
            url=f"/materials/{fingerprint}?podcast_error=generation_failed",
            status_code=303,
        )

    return RedirectResponse(url=f"/materials/{fingerprint}#podcasts", status_code=303)


@router.post("/materials/{fingerprint}/regenerate", response_class=RedirectResponse)
def regenerate_from_materials(
    fingerprint: str,
    request: Request,  # noqa: ARG001 — kept for handler signature parity
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> RedirectResponse:
    """Trigger prep regeneration from the per-job materials page.

    Mirrors the gating of ``board_actions.regenerate`` (404 / idempotent
    prep_in_progress / queue cap) but redirects to ``/materials/`` rather than
    returning the dashboard's HTMX row. Side effects route through the shared
    ``_execute_regenerate`` helper so prep-launch state stays in one place.
    """
    from findajob.web.routes.board_actions import (
        MAX_CONCURRENT_PREPS,
        _execute_regenerate,
        _prep_in_flight,
    )

    job = db.execute(
        "SELECT id, title, company, url, stage, prep_folder_path FROM jobs WHERE fingerprint=?",
        (fingerprint,),
    ).fetchone()
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")

    if job["stage"] == "prep_in_progress":
        return RedirectResponse(url=f"/materials/{fingerprint}", status_code=303)

    if _prep_in_flight(db) >= MAX_CONCURRENT_PREPS:
        return RedirectResponse(url="/materials/?regen_error=queue_full", status_code=303)

    _execute_regenerate(db, job, source_event="web_regen_dispatched_from_materials")

    return RedirectResponse(url="/materials/", status_code=303)


@router.post("/materials/{fingerprint}/rerun-interview-prep", response_class=RedirectResponse)
def rerun_interview_prep_from_materials(
    fingerprint: str,
    request: Request,  # noqa: ARG001 — kept for handler signature parity
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> RedirectResponse:
    """Re-run interview prep from the per-job materials page (#875).

    For interview-stage jobs that were prepped before study-guide /
    flashcard / podcast features shipped, or where the operator wants
    fresh artifacts after receiving panel info.  Same subprocess as
    ``POST /board/jobs/{fp}/interview`` (re-click path), gated by
    spend ceiling + per-job concurrency via ``background_tasks``.
    """
    from findajob.background_tasks import find_active_for_subject
    from findajob.spend_ceiling import check_launch_gate
    from findajob.web.routes.board_actions import _launch_interview_prep_subprocess

    job = db.execute(
        "SELECT id, fingerprint, title, company, url, stage FROM jobs WHERE fingerprint=?",
        (fingerprint,),
    ).fetchone()
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")

    if job["stage"] != "interview":
        raise HTTPException(
            status_code=409,
            detail="Re-run interview prep only valid for interview-stage jobs",
        )

    if find_active_for_subject(db, job["id"], "interview_prep"):
        return RedirectResponse(
            url=f"/materials/{fingerprint}?interview_rerun_error=already_running",
            status_code=303,
        )

    refusal = check_launch_gate(db)
    if refusal is not None:
        return RedirectResponse(
            url=f"/materials/{fingerprint}?interview_rerun_error=spend_ceiling",
            status_code=303,
        )

    _launch_interview_prep_subprocess(db, job)

    return RedirectResponse(url=f"/materials/{fingerprint}", status_code=303)


@router.post("/materials/{fingerprint}/continue-prep", response_class=RedirectResponse)
def continue_prep_from_materials(
    fingerprint: str,
    request: Request,  # noqa: ARG001 — kept for handler signature parity
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> RedirectResponse:
    """Plain-form wrapper around ``board_actions.continue_prep`` for the
    briefing-first gate UI on ``/materials/{fp}/`` (#691).

    The dashboard-flow ``POST /board/jobs/{fp}/continue-prep`` returns an
    HTMX-shaped ``<tr>`` for in-place row swap. The materials page is
    server-rendered HTML, not HTMX-driven; a plain form POST to that
    endpoint would land the operator on a page whose body is a bare
    ``<tr>``. This wrapper applies the same gates (404 / idempotent /
    409 / 402 / 429) and dispatches the same Phase B subprocess via
    the shared ``_launch_prep_subprocess``, then returns a 303 redirect
    back to ``/materials/`` so the operator lands somewhere coherent.

    Queue-full and spend-ceiling refusals redirect with a query-param
    error signal that ``materials_index`` can surface via a banner
    (mirrors ``regenerate_from_materials``'s ``?regen_error=queue_full``
    convention).
    """
    from findajob.spend_ceiling import check_launch_gate
    from findajob.web.routes.board_actions import (
        MAX_CONCURRENT_PREPS,
        _launch_prep_subprocess,
        _prep_in_flight,
    )

    job = db.execute(
        "SELECT id, fingerprint, title, company, url, stage FROM jobs WHERE fingerprint=?",
        (fingerprint,),
    ).fetchone()
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")

    # Idempotent on already-advanced rows — operator double-click lands
    # safely on /materials/{fp}/ which renders the in-flight state.
    if job["stage"] in ("prep_in_progress", "materials_drafted"):
        return RedirectResponse(url=f"/materials/{fingerprint}", status_code=303)

    if job["stage"] != "briefing_ready":
        raise HTTPException(
            status_code=409,
            detail="Continue-prep only valid for jobs at stage='briefing_ready'",
        )

    refusal = check_launch_gate(db)
    if refusal is not None:
        # Surface via /materials/ banner. The exact param name + UI
        # follows the same convention as `?regen_error=queue_full`.
        return RedirectResponse(url="/materials/?continue_prep_error=spend_ceiling", status_code=303)

    if _prep_in_flight(db) >= MAX_CONCURRENT_PREPS:
        return RedirectResponse(url="/materials/?continue_prep_error=queue_full", status_code=303)

    now = datetime.now(UTC).isoformat()
    db.execute(
        "UPDATE jobs SET stage='prep_in_progress', stage_updated=?, updated_at=? WHERE id=?",
        (now, now, job["id"]),
    )
    db.commit()
    from findajob.audit import log_event, write_audit

    write_audit(db, job["id"], "stage", job["stage"], "prep_in_progress")
    log_event(
        "web_continue_prep_dispatched_from_materials",
        job_id=job["id"],
        company=job["company"],
        title=job["title"],
    )

    _launch_prep_subprocess(db, job, kind="prep_phase_b", extra_args=("--phase=b",))

    return RedirectResponse(url=f"/materials/{fingerprint}", status_code=303)


@router.post("/materials/{fingerprint}/reject", response_class=RedirectResponse)
def reject_from_materials(
    fingerprint: str,
    request: Request,  # noqa: ARG001 — kept for handler signature parity
    reason: str = Form(""),
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> RedirectResponse:
    """Plain-form wrapper around ``handle_rejection`` for the briefing-gate UI.

    The dashboard-flow ``POST /board/jobs/{fp}/reject`` returns
    ``HTMLResponse("")`` (a blank body) — fine for HTMX swap-out, broken
    for a plain form. Mirrors the rationale in
    :func:`continue_prep_from_materials`: same business logic
    (``handle_rejection`` + ``notify_waitlist_resurface``), 303 redirect
    to ``/materials/`` so the row drops off the In-flight section.

    Idempotent on already-rejected rows — second submit is a no-op
    redirect.
    """
    from findajob.actions import handle_rejection, notify_waitlist_resurface

    job = db.execute(
        "SELECT id, fingerprint, title, company, url, stage, relevance_score, prep_folder_path "
        "FROM jobs WHERE fingerprint=?",
        (fingerprint,),
    ).fetchone()
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")
    if job["stage"] == "rejected":
        return RedirectResponse(url="/materials/", status_code=303)

    handle_rejection(db, job, (reason or "").strip() or "Other")
    notify_waitlist_resurface(db, job["company"])
    return RedirectResponse(url="/materials/", status_code=303)


@router.get("/jobs/{fingerprint}/jd", response_class=HTMLResponse)
def jd_view(
    fingerprint: str,
    request: Request,
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> HTMLResponse:
    row = db.execute(
        "SELECT title, company, raw_jd_text FROM jobs WHERE fingerprint = ?",
        (fingerprint,),
    ).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="job not found")
    body = (row["raw_jd_text"] or "").strip()
    header = f"# {row['title']}\n\n_{row['company']}_\n\n---\n\n"
    md = header + (body if body else "_No JD text on file._")
    templates = request.app.state.templates
    return templates.TemplateResponse(
        request=request,
        name="base.html",
        context={"_rendered_md": render_markdown(md)},
        headers={"content-type": "text/html; charset=utf-8"},
    )


@router.get("/materials/{fingerprint}/{filename}")
def file_serve(
    fingerprint: str,
    filename: str,
    request: Request,
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
    raw: int = 0,
):
    root: Path = request.app.state.companies_root
    folder = _resolve_folder_with_speculative_fallback(fingerprint, db, root)
    if folder is None:
        raise HTTPException(status_code=404, detail="folder not found")
    candidate = (folder / filename).resolve()
    try:
        candidate.relative_to(folder.resolve())
    except ValueError:
        raise HTTPException(status_code=404, detail="invalid filename") from None
    if not candidate.is_file():
        raise HTTPException(status_code=404, detail="file not found")
    ext = candidate.suffix.lower()
    # ?raw=1 returns the .md / .txt source bytes verbatim — used by the
    # "Copy MD" button on the folder page so what lands on the clipboard
    # is byte-identical to the file on disk (no markdown→HTML→back-to-text
    # round-trip via the rendered prose view).
    if raw and ext in (".md", ".txt"):
        return PlainTextResponse(content=candidate.read_text(encoding="utf-8", errors="replace"))
    if ext == ".md":
        body = candidate.read_text(encoding="utf-8", errors="replace")
        templates = request.app.state.templates
        return templates.TemplateResponse(
            request=request,
            name="base.html",
            context={"_rendered_md": render_markdown(body)},
            headers={"content-type": "text/html; charset=utf-8"},
        )
    if ext == ".txt":
        return PlainTextResponse(content=candidate.read_text(encoding="utf-8", errors="replace"))
    return FileResponse(
        path=candidate,
        filename=candidate.name,
        media_type="application/octet-stream",
        headers={"content-disposition": f'attachment; filename="{candidate.name}"'},
    )


@router.post("/materials/{fingerprint}/files/{filename}", response_class=HTMLResponse)
def edit_save(
    fingerprint: str,
    filename: str,
    request: Request,
    content: str = Form(...),
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> HTMLResponse:
    """Save an edited markdown file and refresh the .docx sibling (#210).

    Validation gates:
      - Folder resolves via folder_resolver (404 otherwise)
      - Filename ends in .md (400 otherwise)
      - Filename does NOT match the snapshot/backup pattern (403 — those are
        read-only audit artifacts written by snapshot_applied_md_files / .bak)
      - Filename classifies to a recognized _GROUP_RULES label (403 otherwise)
      - Path-traversal guard (404 on escape)
      - Stage != 'prep_in_progress' (409 — the prep subprocess may rmtree
        the folder out from under the save)

    Mutations:
      - One-shot {file}.bak captures the pre-edit content if not already present
      - Resume-class files run _linkify_contact_info on submitted content
      - Atomic write via tempfile.mkstemp + os.replace
      - .docx sibling regenerated via render_md_to_docx; has_yaml_frontmatter
        is True only for standard "Briefing" classification (not speculative).
        Pandoc failures surface in the result partial; the .md is still saved.
    """
    root: Path = request.app.state.companies_root
    folder = resolve_folder(fingerprint, db, root)
    if folder is None:
        raise HTTPException(status_code=404, detail="folder not found")

    if not filename.endswith(".md"):
        raise HTTPException(status_code=400, detail="only .md files are editable")
    if _HIDE_FROM_VIEW_RE.search(filename):
        raise HTTPException(status_code=403, detail="snapshots and backups are read-only")
    label, _order = _classify_file(filename)
    if label == _OTHER_LABEL:
        raise HTTPException(status_code=403, detail="this file is not editable")

    target = (folder / filename).resolve()
    try:
        target.relative_to(folder.resolve())
    except ValueError:
        raise HTTPException(status_code=404, detail="invalid filename") from None
    if not target.is_file():
        raise HTTPException(status_code=404, detail="file not found")

    stage_row = db.execute("SELECT stage FROM jobs WHERE fingerprint = ?", (fingerprint,)).fetchone()
    if stage_row is not None and stage_row["stage"] == "prep_in_progress":
        raise HTTPException(
            status_code=409,
            detail="prep is regenerating this folder; try again in a few minutes",
        )

    bak = target.with_suffix(target.suffix + ".bak")
    if not bak.exists():
        shutil.copy2(target, bak)

    if label == "Resume":
        content = _linkify_contact_info(content)

    fd, tmp_name = tempfile.mkstemp(
        prefix=target.name + ".",
        suffix=".tmp",
        dir=str(target.parent),
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as fh:
            fh.write(content)
        os.replace(tmp_name, target)
    except Exception:
        if os.path.exists(tmp_name):
            os.unlink(tmp_name)
        raise

    docx_path = target.with_suffix(".docx")
    pandoc_error: str | None = None
    if docx_path.is_file():
        try:
            render_md_to_docx(target, docx_path, has_yaml_frontmatter=(label == "Briefing"))
        except subprocess.CalledProcessError as exc:
            stderr = (exc.stderr or b"").decode("utf-8", errors="replace").strip()
            pandoc_error = stderr.splitlines()[-1] if stderr else f"pandoc exited {exc.returncode}"
        except FileNotFoundError as exc:
            # pandoc binary missing (PANDOC misconfigured or not installed).
            # The .md write already succeeded; surface the infra error in the partial.
            pandoc_error = f"pandoc binary not found ({exc.filename or 'unknown path'})"
        except OSError as exc:
            # Catch-all for other subprocess infra failures (permission denied, etc).
            pandoc_error = f"pandoc invocation failed: {exc.strerror or type(exc).__name__}"

    saved_at = datetime.now(UTC).strftime("%H:%M UTC")
    if pandoc_error:
        outcome = "error"
        message = (
            f".md saved at {saved_at} but .docx regen failed: {pandoc_error}. The .docx is stale; save again to retry."
        )
    else:
        outcome = "success"
        message = f"Saved {filename} at {saved_at}."

    templates = request.app.state.templates
    return templates.TemplateResponse(
        request=request,
        name="config/_save_result.html",
        context={"outcome": outcome, "message": message},
    )
