"""Materials viewer routes: /, /materials/{fp}, /materials/{fp}/{file}."""

from __future__ import annotations

import os
import re
import shutil
import sqlite3
import subprocess
import tempfile
from datetime import UTC, datetime
from pathlib import Path

from fastapi import APIRouter, Depends, Form, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, PlainTextResponse, RedirectResponse

from findajob.prep.docx_postprocess import _linkify_contact_info
from findajob.prep.docx_render import render_md_to_docx
from findajob.web.folder_resolver import resolve_folder
from findajob.web.markdown import render_markdown

router = APIRouter()


# Document-type classification for the materials folder view. Filename
# patterns generated by prep_application.py / find_contacts.py / triage.py:
#   "JD - {Company} - {Title}.txt"             — Job Description
#   "Review Checklist - {Company} - {Title}.md"
#   "{Display} Briefing - {Company} - {Title} - {ts}.{md,docx}"
#   "{Display} Resume - {Company} - {Title} - {ts}.{md,docx}"
#   "{Display} Resume Changes - {Company} - {Title} - {ts}.md"
#   "{Display} Cover - {Company} - {Title} - {ts}.{md,docx}"
#   "{Display} Critique - {Company} - {Title} - {ts}.md"
#   "{Display} Outreach to {Recipient} - {Company} - {ts}.txt"
#   "briefing.md"                              — speculative submission folder
# The classifier checks substrings rather than parsing the full pattern so
# changes to display_name / company / title don't break grouping.
_GROUP_RULES: list[tuple[str, str, int]] = [
    # (substring/marker, label, sort order)
    ("JD - ", "Job Description", 1),
    ("briefing.md", "Briefing (speculative)", 2),
    (" Briefing - ", "Briefing", 2),
    (" Resume Changes - ", "Resume Changes", 4),
    (" Resume - ", "Resume", 3),
    (" Cover - ", "Cover Letter", 5),
    (" Outreach to ", "Outreach", 6),
    (" Critique - ", "Recruiter Critique", 7),
    ("Review Checklist - ", "Review Checklist", 8),
]
_OTHER_LABEL = "Other"
_OTHER_ORDER = 99
_OUTREACH_RECIPIENT_RE = re.compile(r" Outreach to ([^-]+?) - ")
# Hide audit-snapshot (.applied-YYYY-MM-DD.md, written on apply transition #210)
# and edit-backup (.bak, written on first edit via /materials/{fp}/files/{name})
# files from the per-folder view — they exist for audit/recovery, not day-to-day display.
_HIDE_FROM_VIEW_RE = re.compile(r"\.applied-\d{4}-\d{2}-\d{2}\.md$|\.bak$")
_APPLIED_DATE_RE = re.compile(r"\.applied-(\d{4}-\d{2}-\d{2})\.md$")

# Stages where the materials have already been sent — banner reminds the
# operator that edits don't change what the employer received.
POST_APPLIED_STAGES = frozenset({"applied", "interview", "offer", "not_selected", "withdrawn"})


def _latest_applied_date(folder: Path) -> str | None:
    """Return the most recent date (YYYY-MM-DD) seen in *.applied-DATE.md
    snapshot filenames, or None if no snapshots exist."""
    dates = []
    for p in folder.iterdir():
        if not p.is_file():
            continue
        m = _APPLIED_DATE_RE.search(p.name)
        if m:
            dates.append(m.group(1))
    return max(dates) if dates else None


# Plain-language explanation per group: what it is + when to use it. Templates
# interpolate {title}, {company}, {recipient} where applicable. Goal is to be
# specific enough that a non-power-user (a beta tester opening this folder for
# the first time) understands which docs are submission artifacts vs internal
# prep notes — the latter must NEVER read as "send this to the employer."
_GROUP_DESCRIPTIONS: dict[str, str] = {
    "Job Description": "The original posting text. Reference while you tailor — not something you send back.",
    "Briefing": (
        "Plain-language brief on {company}, the {title} role, and how your background lines up. "
        "Read first — it informs the resume, cover letter, and interview prep. For your eyes only."
    ),
    "Briefing (speculative)": (
        "Deep-research brief on {company} for cold outreach. Use as the source for the outreach drafts "
        "and any conversations you start. Not something you send."
    ),
    "Resume": "Your resume tailored to {title} at {company}. The .docx is what you submit with the application.",
    "Resume Changes": (
        "Diff-style explanation of how the tailored resume differs from your master resume — "
        "a sanity check so you know what was emphasized or trimmed before you submit. For your eyes only."
    ),
    "Cover Letter": "Cover letter drafted for {title} at {company}. The .docx is what you submit with the application.",
    "Outreach": (
        "Short cold-outreach drafts for people who can refer you or surface the role internally. "
        "Paste into LinkedIn DM or email."
    ),
    "Recruiter Critique": (
        "A simulated recruiter's red-team take on the tailored resume and cover. Read it as a "
        "'what would a skeptic pick on' pass before submitting. For your eyes only."
    ),
    "Review Checklist": (
        "Pre-flight checklist of things to verify before you submit — formatting, claims, contact info."
    ),
}

# Per-(group, ext) one-liner shown on each file row. Tells the user what to
# *do with this specific file* — distinct from the group description above
# which tells them what the doc *is*. Empty string means "fall back to the
# generic ext blurb in the template."
_FILE_HINTS: dict[tuple[str, str], str] = {
    ("Resume", "docx"): "MS Word — submit this with the application",
    ("Resume", "md"): "Markdown source — preview in browser, or Copy MD into Google Docs",
    ("Cover Letter", "docx"): "MS Word — submit this with the application",
    ("Cover Letter", "md"): "Markdown source — preview in browser, or Copy MD into Google Docs",
    ("Briefing", "docx"): "MS Word — printable copy of the briefing",
    ("Briefing", "md"): "Markdown source — preview in browser",
    ("Briefing (speculative)", "md"): "Markdown source — preview in browser",
    ("Outreach", "txt"): "Plain text — paste into LinkedIn DM or email",
    ("Job Description", "txt"): "Plain text — the original posting",
    ("Resume Changes", "md"): "Markdown source — preview in browser",
    ("Recruiter Critique", "md"): "Markdown source — preview in browser",
    ("Review Checklist", "md"): "Markdown source — preview in browser",
}


def _classify_file(name: str) -> tuple[str, int]:
    """Return (group label, sort order) for a filename. Falls back to 'Other'."""
    if name == "briefing.md":
        return ("Briefing (speculative)", 2)
    for marker, label, order in _GROUP_RULES:
        if marker in name:
            return (label, order)
    return (_OTHER_LABEL, _OTHER_ORDER)


def _human_size(n: int) -> str:
    """Compact size for the UI: B / K / M only — folders never reach G."""
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n // 1024} K"
    return f"{n // (1024 * 1024)} M"


def _human_mtime(ts: float) -> str:
    """Render an mtime as 'YYYY-MM-DD HH:MM' UTC for stable comparison across
    container TZs. Operator + testers all read this in their browser TZ via
    the fact it shows the same UTC clock; precise relative time isn't worth
    the JS dependency."""
    return datetime.fromtimestamp(ts, tz=UTC).strftime("%Y-%m-%d %H:%M UTC")


def _format_description(label: str, title: str, company: str) -> str:
    """Render the group description with title/company interpolated. Falls
    back to empty string if no description is registered (e.g. 'Other')."""
    template = _GROUP_DESCRIPTIONS.get(label, "")
    if not template:
        return ""
    return template.format(title=title or "this role", company=company or "this company")


def _group_files(folder: Path, title: str = "", company: str = "") -> list[dict]:
    """Group files in a prep folder by document type, ordered for the
    natural reading sequence (JD first, Review Checklist last). Each group
    carries a plain-language description; each file row carries a
    per-(group, ext) hint plus its display affordance — .md/.txt render
    inline (View), everything else downloads (Download)."""
    by_label: dict[str, dict] = {}
    for p in sorted(folder.iterdir()):
        if not p.is_file():
            continue
        if _HIDE_FROM_VIEW_RE.search(p.name):
            continue
        label, order = _classify_file(p.name)
        ext = p.suffix.lower().lstrip(".")
        # .md and .txt render inline via the file_serve route; .docx and
        # everything else are forced downloads (Content-Disposition: attachment).
        is_view = ext in ("md", "txt")
        recipient = None
        if " Outreach to " in p.name:
            m = _OUTREACH_RECIPIENT_RE.search(p.name)
            if m:
                recipient = m.group(1).strip()
        try:
            stat = p.stat()
            size = _human_size(stat.st_size)
            mtime = _human_mtime(stat.st_mtime)
        except OSError:
            size = ""
            mtime = ""
        entry = {
            "name": p.name,
            "ext": ext,
            "is_view": is_view,
            "recipient": recipient,
            "size": size,
            "mtime": mtime,
            "hint": _FILE_HINTS.get((label, ext), ""),
        }
        by_label.setdefault(
            label,
            {
                "label": label,
                "order": order,
                "description": _format_description(label, title, company),
                "files": [],
            },
        )
        by_label[label]["files"].append(entry)

    # Within each group, order: .md first (View), then .txt (View),
    # then .docx (Download), then anything else.
    ext_priority = {"md": 0, "txt": 1, "docx": 2}
    for g in by_label.values():
        g["files"].sort(key=lambda f: (ext_priority.get(f["ext"], 99), f["name"]))

    return sorted(by_label.values(), key=lambda g: (g["order"], g["label"]))


def get_db() -> sqlite3.Connection:  # pragma: no cover — overridden in app factory
    raise NotImplementedError("DB dependency must be overridden by create_app()")


_INDEX_QUERY_SECTIONS = [
    ("In flight", "stage IN ('materials_drafted', 'prep_in_progress')", "created_at DESC"),
    ("Applied", "stage IN ('applied', 'interview', 'offer')", "COALESCE(stage_updated, created_at) DESC"),
    ("Waitlisted", "stage = 'waitlisted'", "created_at DESC"),
]
_REJECTED_CLAUSE = "stage IN ('rejected', 'not_selected')"
_PER_SECTION_CAP = 50


def _fetch_section(db: sqlite3.Connection, where: str, order: str) -> list[sqlite3.Row]:
    return db.execute(
        f"SELECT fingerprint, title, company, stage, fit_score, created_at, stage_updated "
        f"FROM jobs WHERE {where} ORDER BY {order} LIMIT {_PER_SECTION_CAP + 1}"
    ).fetchall()


@router.get("/materials/", response_class=HTMLResponse)
def materials_index(
    request: Request,
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
    regen_error: str = "",
) -> HTMLResponse:
    sections = []
    for name, where, order in _INDEX_QUERY_SECTIONS:
        rows = _fetch_section(db, where, order)
        overflow = len(rows) > _PER_SECTION_CAP
        sections.append({"name": name, "rows": rows[:_PER_SECTION_CAP], "overflow": overflow})
    rejected_rows = _fetch_section(db, _REJECTED_CLAUSE, "created_at DESC")
    rejected = {
        "rows": rejected_rows[:_PER_SECTION_CAP],
        "overflow": len(rejected_rows) > _PER_SECTION_CAP,
        "count": len(rejected_rows) if len(rejected_rows) <= _PER_SECTION_CAP else f"{_PER_SECTION_CAP}+",
    }
    templates = request.app.state.templates
    return templates.TemplateResponse(
        request=request,
        name="materials/index.html",
        context={"sections": sections, "rejected": rejected, "regen_error": regen_error},
    )


def _resolve_folder_with_speculative_fallback(fingerprint: str, db: sqlite3.Connection, root: Path) -> Path | None:
    """resolve_folder + synthetic-row fallback to speculative_briefing_folder.

    Synthetic rows have no prep_folder_path until flag-for-prep, but the
    speculative briefing folder exists on disk from approve-time. Both the
    folder index and the per-file route need to reach into it; keeping the
    fallback in one place avoids the drift that produced #589 (folder index
    rendered the speculative briefing row, single-file route 404'd).

    Returns None when the row has no usable folder. Callers decide UX:
    folder_view redirects synthetic-no-folder rows to /jd, file_serve 404s.
    """
    folder = resolve_folder(fingerprint, db, root)
    if folder is not None:
        return folder
    synth_row = db.execute(
        "SELECT synthetic, speculative_briefing_folder FROM jobs WHERE fingerprint = ?",
        (fingerprint,),
    ).fetchone()
    if synth_row is None or not synth_row["synthetic"]:
        return None
    spec_folder_name = synth_row["speculative_briefing_folder"]
    if not spec_folder_name:
        return None
    spec_folder = (root / spec_folder_name).resolve()
    try:
        spec_folder.relative_to(root.resolve())
    except ValueError:
        return None  # path-traversal guard on the stored folder name
    if not spec_folder.is_dir():
        return None
    return spec_folder


@router.get("/materials/{fingerprint}", response_class=HTMLResponse, response_model=None)
def folder_view(
    fingerprint: str,
    request: Request,
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> HTMLResponse | RedirectResponse:
    from findajob.cost_rollups import per_job_breakdown

    root: Path = request.app.state.companies_root
    folder = _resolve_folder_with_speculative_fallback(fingerprint, db, root)
    if folder is None:
        # Synthetic rows with no usable briefing folder land on the role-card
        # description page; non-synthetic missing-folder is a 404.
        synth_row = db.execute(
            "SELECT synthetic FROM jobs WHERE fingerprint = ?",
            (fingerprint,),
        ).fetchone()
        if synth_row is not None and synth_row["synthetic"]:
            return RedirectResponse(url=f"/jobs/{fingerprint}/jd", status_code=303)
        raise HTTPException(status_code=404, detail="folder not found")
    row = db.execute(
        "SELECT id, title, company, stage, stage_updated FROM jobs WHERE fingerprint = ?",
        (fingerprint,),
    ).fetchone()
    title = row["title"] if row else ""
    company = row["company"] if row else ""
    groups = _group_files(folder, title=title, company=company)

    # Per-operation cost breakdown (only if cost_log exists; fail open)
    breakdown = []
    breakdown_total = None
    if row is not None:
        try:
            breakdown = per_job_breakdown(db, row["id"])
            if breakdown:
                breakdown_total = sum(r.cost_usd for r in breakdown)
        except sqlite3.OperationalError:
            # Test fixtures may lack cost_log.
            breakdown = []

    stage = row["stage"] if row else ""
    is_post_applied = stage in POST_APPLIED_STAGES
    applied_date = _latest_applied_date(folder) if is_post_applied else None

    templates = request.app.state.templates
    return templates.TemplateResponse(
        request=request,
        name="materials/folder.html",
        context={
            "fingerprint": fingerprint,
            "folder_name": folder.name,
            "title": title,
            "company": company,
            "stage": stage,
            "last_generated_iso": row["stage_updated"] if row else None,
            "groups": groups,
            "breakdown": breakdown,
            "breakdown_total": breakdown_total,
            "is_post_applied": is_post_applied,
            "applied_date": applied_date,
        },
    )


@router.post("/materials/{fingerprint}/regenerate", response_class=RedirectResponse)
def regenerate_from_materials(
    fingerprint: str,
    request: Request,  # noqa: ARG001 — kept for handler signature parity
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> RedirectResponse:
    """Trigger prep regeneration from the per-job materials page.

    Mirrors the gating of ``board_actions.regenerate`` (404 / idempotent
    prep_in_progress / queue cap) but redirects to ``/materials/`` rather than
    returning the dashboard's HTMX row. Side effects route through the shared
    ``_execute_regenerate`` helper so prep-launch state stays in one place.
    """
    from findajob.web.routes.board_actions import (
        MAX_CONCURRENT_PREPS,
        _execute_regenerate,
        _prep_in_flight,
    )

    job = db.execute(
        "SELECT id, title, company, url, stage, prep_folder_path FROM jobs WHERE fingerprint=?",
        (fingerprint,),
    ).fetchone()
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")

    if job["stage"] == "prep_in_progress":
        return RedirectResponse(url=f"/materials/{fingerprint}", status_code=303)

    if _prep_in_flight(db) >= MAX_CONCURRENT_PREPS:
        return RedirectResponse(url="/materials/?regen_error=queue_full", status_code=303)

    _execute_regenerate(db, job, source_event="web_regen_dispatched_from_materials")

    return RedirectResponse(url="/materials/", status_code=303)


@router.get("/jobs/{fingerprint}/jd", response_class=HTMLResponse)
def jd_view(
    fingerprint: str,
    request: Request,
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> HTMLResponse:
    row = db.execute(
        "SELECT title, company, raw_jd_text FROM jobs WHERE fingerprint = ?",
        (fingerprint,),
    ).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="job not found")
    body = (row["raw_jd_text"] or "").strip()
    header = f"# {row['title']}\n\n_{row['company']}_\n\n---\n\n"
    md = header + (body if body else "_No JD text on file._")
    templates = request.app.state.templates
    return templates.TemplateResponse(
        request=request,
        name="base.html",
        context={"_rendered_md": render_markdown(md)},
        headers={"content-type": "text/html; charset=utf-8"},
    )


@router.get("/materials/{fingerprint}/{filename}")
def file_serve(
    fingerprint: str,
    filename: str,
    request: Request,
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
    raw: int = 0,
):
    root: Path = request.app.state.companies_root
    folder = _resolve_folder_with_speculative_fallback(fingerprint, db, root)
    if folder is None:
        raise HTTPException(status_code=404, detail="folder not found")
    candidate = (folder / filename).resolve()
    try:
        candidate.relative_to(folder.resolve())
    except ValueError:
        raise HTTPException(status_code=404, detail="invalid filename") from None
    if not candidate.is_file():
        raise HTTPException(status_code=404, detail="file not found")
    ext = candidate.suffix.lower()
    # ?raw=1 returns the .md / .txt source bytes verbatim — used by the
    # "Copy MD" button on the folder page so what lands on the clipboard
    # is byte-identical to the file on disk (no markdown→HTML→back-to-text
    # round-trip via the rendered prose view).
    if raw and ext in (".md", ".txt"):
        return PlainTextResponse(content=candidate.read_text(encoding="utf-8", errors="replace"))
    if ext == ".md":
        body = candidate.read_text(encoding="utf-8", errors="replace")
        templates = request.app.state.templates
        return templates.TemplateResponse(
            request=request,
            name="base.html",
            context={"_rendered_md": render_markdown(body)},
            headers={"content-type": "text/html; charset=utf-8"},
        )
    if ext == ".txt":
        return PlainTextResponse(content=candidate.read_text(encoding="utf-8", errors="replace"))
    return FileResponse(
        path=candidate,
        filename=candidate.name,
        media_type="application/octet-stream",
        headers={"content-disposition": f'attachment; filename="{candidate.name}"'},
    )


@router.post("/materials/{fingerprint}/files/{filename}", response_class=HTMLResponse)
def edit_save(
    fingerprint: str,
    filename: str,
    request: Request,
    content: str = Form(...),
    db: sqlite3.Connection = Depends(get_db),  # noqa: B008
) -> HTMLResponse:
    """Save an edited markdown file and refresh the .docx sibling (#210).

    Validation gates:
      - Folder resolves via folder_resolver (404 otherwise)
      - Filename ends in .md (400 otherwise)
      - Filename does NOT match the snapshot/backup pattern (403 — those are
        read-only audit artifacts written by snapshot_applied_md_files / .bak)
      - Filename classifies to a recognized _GROUP_RULES label (403 otherwise)
      - Path-traversal guard (404 on escape)
      - Stage != 'prep_in_progress' (409 — the prep subprocess may rmtree
        the folder out from under the save)

    Mutations:
      - One-shot {file}.bak captures the pre-edit content if not already present
      - Resume-class files run _linkify_contact_info on submitted content
      - Atomic write via tempfile.mkstemp + os.replace
      - .docx sibling regenerated via render_md_to_docx; has_yaml_frontmatter
        is True only for standard "Briefing" classification (not speculative).
        Pandoc failures surface in the result partial; the .md is still saved.
    """
    root: Path = request.app.state.companies_root
    folder = resolve_folder(fingerprint, db, root)
    if folder is None:
        raise HTTPException(status_code=404, detail="folder not found")

    if not filename.endswith(".md"):
        raise HTTPException(status_code=400, detail="only .md files are editable")
    if _HIDE_FROM_VIEW_RE.search(filename):
        raise HTTPException(status_code=403, detail="snapshots and backups are read-only")
    label, _order = _classify_file(filename)
    if label == _OTHER_LABEL:
        raise HTTPException(status_code=403, detail="this file is not editable")

    target = (folder / filename).resolve()
    try:
        target.relative_to(folder.resolve())
    except ValueError:
        raise HTTPException(status_code=404, detail="invalid filename") from None
    if not target.is_file():
        raise HTTPException(status_code=404, detail="file not found")

    stage_row = db.execute("SELECT stage FROM jobs WHERE fingerprint = ?", (fingerprint,)).fetchone()
    if stage_row is not None and stage_row["stage"] == "prep_in_progress":
        raise HTTPException(
            status_code=409,
            detail="prep is regenerating this folder; try again in a few minutes",
        )

    bak = target.with_suffix(target.suffix + ".bak")
    if not bak.exists():
        shutil.copy2(target, bak)

    if label == "Resume":
        content = _linkify_contact_info(content)

    fd, tmp_name = tempfile.mkstemp(
        prefix=target.name + ".",
        suffix=".tmp",
        dir=str(target.parent),
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as fh:
            fh.write(content)
        os.replace(tmp_name, target)
    except Exception:
        if os.path.exists(tmp_name):
            os.unlink(tmp_name)
        raise

    docx_path = target.with_suffix(".docx")
    pandoc_error: str | None = None
    if docx_path.is_file():
        try:
            render_md_to_docx(target, docx_path, has_yaml_frontmatter=(label == "Briefing"))
        except subprocess.CalledProcessError as exc:
            stderr = (exc.stderr or b"").decode("utf-8", errors="replace").strip()
            pandoc_error = stderr.splitlines()[-1] if stderr else f"pandoc exited {exc.returncode}"
        except FileNotFoundError as exc:
            # pandoc binary missing (PANDOC misconfigured or not installed).
            # The .md write already succeeded; surface the infra error in the partial.
            pandoc_error = f"pandoc binary not found ({exc.filename or 'unknown path'})"
        except OSError as exc:
            # Catch-all for other subprocess infra failures (permission denied, etc).
            pandoc_error = f"pandoc invocation failed: {exc.strerror or type(exc).__name__}"

    saved_at = datetime.now(UTC).strftime("%H:%M UTC")
    if pandoc_error:
        outcome = "error"
        message = (
            f".md saved at {saved_at} but .docx regen failed: {pandoc_error}. The .docx is stale; save again to retry."
        )
    else:
        outcome = "success"
        message = f"Saved {filename} at {saved_at}."

    templates = request.app.state.templates
    return templates.TemplateResponse(
        request=request,
        name="config/_save_result.html",
        context={"outcome": outcome, "message": message},
    )
